# Generated by Django 6.0.2 on 2026-02-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Госномер"
                    ),
                ),
                ("brand", models.CharField(max_length=30, verbose_name="Марка")),
                ("model", models.CharField(max_length=30, verbose_name="Модель")),
                ("color", models.CharField(max_length=30, verbose_name="Цвет")),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=30, verbose_name="Фамилия")),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
            ],
            options={
                "verbose_name": "Владелец",
                "verbose_name_plural": "Владельцы",
            },
        ),
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер удостоверения"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("A", "Мотоцикл"),
                            ("B", "Легковой автомобиль"),
                            ("C", "Грузовой автомобиль"),
                            ("D", "Автобус"),
                            ("M", "Мопед"),
                        ],
                        max_length=1,
                        verbose_name="Категория",
                    ),
                ),
                ("issue_date", models.DateTimeField(verbose_name="Дата выдачи")),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license",
                        to="practice3_app.owner",
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Водительское удостоверение",
                "verbose_name_plural": "Водительские удостоверения",
            },
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(verbose_name="Дата начала владения"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания владения"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="practice3_app.car",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="practice3_app.owner",
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Владение",
                "verbose_name_plural": "Владения",
                "unique_together": {("owner", "car")},
            },
        ),
    ]
