# Generated by Django 6.0.2 on 2026-02-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название отеля"),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Адрес")),
                (
                    "city",
                    models.CharField(
                        default="Москва", max_length=100, verbose_name="Город"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "stars",
                    models.IntegerField(default=3, verbose_name="Количество звезд"),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за ночь"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Отель",
                "verbose_name_plural": "Отели",
            },
        ),
    ]
