# Generated by Django 6.0.2 on 2026-02-11 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels_app", "0002_amenity_alter_hotel_options_remove_hotel_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name": "Услуги", "verbose_name_plural": "Услуги"},
        ),
        migrations.AlterModelOptions(
            name="hotel",
            options={"verbose_name": "Отель", "verbose_name_plural": "Отели"},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="roomtype",
            options={
                "verbose_name": "Тип номера",
                "verbose_name_plural": "Типы номеров",
            },
        ),
        migrations.AddField(
            model_name="hotel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Услуги"),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, to="hotels_app.amenity", verbose_name="Услуги"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="check_in",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="check_out",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="hotels_app.room",
                verbose_name="Бронирование",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Забронировано"),
                    ("checked_in", "Заселился"),
                    ("checked_out", "Выселился"),
                    ("cancelled", "Отменен"),
                ],
                default="reserved",
                max_length=20,
                verbose_name="Забронировано",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Бронирование",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="period_from",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="period_to",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="hotels_app.room",
                verbose_name="Отзывы",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="hotels_app.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="hotels_app.roomtype",
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="capacity",
            field=models.PositiveIntegerField(verbose_name="Вместимость"),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_types",
                to="hotels_app.hotel",
                verbose_name="Отель",
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=9, verbose_name="Цена"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("hotel", "number")},
        ),
    ]
