# Generated by Django 5.1 on 2025-12-06 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15, verbose_name='Гос. номер')),
                ('make', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('birth_date', models.DateField(null=True, verbose_name='Дата_рождения')),
            ],
        ),
        migrations.CreateModel(
            name='CarLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер_удостоверения')),
                ('type', models.CharField(max_length=10, verbose_name='Тип')),
                ('issue_date', models.DateField(verbose_name='Дата_выдачи')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='car_app.carowner', verbose_name='Id_владельца')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата_начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата_окончания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car', verbose_name='Id_автомобиля')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.carowner', verbose_name='Id_владельца')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(related_name='cars', through='car_app.CarOwnership', to='car_app.carowner', verbose_name='Владельцы'),
        ),
    ]
