site_name: "ЛР1 — Работа с сокетами"
nav:
  - Главная: docs/index.md
  - Задание 1: docs/task1.md
  - Задание 2: docs/task2.md
  - Задание 3: docs/task3.md
  - Задание 4: docs/task4.md
  - Задание 5: docs/task5.md
docs_dir: students/k3341/laboratory_works/Dzhavatov_Ilyas/laboratory_work_1  # путь к папке с md
theme: readthedocs
