# Generated by Django 4.2.16 on 2026-01-13 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parks_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objectzone",
            old_name="object_id",
            new_name="object",
        ),
    ]
