# Generated by Django 4.2.16 on 2026-01-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parks_app", "0002_rename_object_id_objectzone_object"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantwateringschedule",
            options={
                "verbose_name": "Plant Watering Schedule",
                "verbose_name_plural": "Plant Watering Schedules",
            },
        ),
        migrations.AlterField(
            model_name="plantwateringschedule",
            name="plant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watering_schedule",
                to="parks_app.plant",
            ),
        ),
    ]
