# Generated by Django 4.2.16 on 2025-12-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parks_app", "0007_alter_contract_enterprise_alter_contract_object"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="enterprise",
        ),
        migrations.AddField(
            model_name="enterprise",
            name="services",
            field=models.ManyToManyField(
                related_name="enterprises", to="parks_app.services"
            ),
        ),
    ]
