# Generated by Django 4.2.16 on 2025-12-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parks_app", "0008_remove_services_enterprise_enterprise_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="is_serviced",
        ),
        migrations.AlterField(
            model_name="contract",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="parks_app.object",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plantplacement",
            unique_together={("zone", "unique_number")},
        ),
        migrations.AlterUniqueTogether(
            name="plantworkerassignment",
            unique_together={("plant", "date")},
        ),
    ]
