# Generated by Django 4.2.16 on 2025-12-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parks_app", "0009_remove_object_is_serviced_alter_contract_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectWorkerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_assignments",
                        to="parks_app.object",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_assignments",
                        to="parks_app.worker",
                    ),
                ),
            ],
        ),
    ]
