# Generated by Django 6.0 on 2026-01-10 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Текст задания')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('due_date', models.DateTimeField(verbose_name='Крайний срок выполнения')),
                ('penalty_info', models.TextField(blank=True, verbose_name='Информация о штрафах')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('text', models.TextField(verbose_name='Текст решения')),
                ('grade', models.IntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Оценка')),
                ('is_late', models.BooleanField(default=False, verbose_name='Сдано с опозданием')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.homework', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Сдача домашнего задания',
                'verbose_name_plural': 'Сдачи домашних заданий',
                'ordering': ['-submission_date'],
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
