# Generated by Django 3.2.19 on 2025-11-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cleaningschedule',
            unique_together={('staff', 'floor', 'day_of_week')},
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.hotelservice', verbose_name='Услуга')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.staff', verbose_name='Сотрудник')),
            ],
            options={
                'unique_together': {('service', 'staff')},
            },
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='staff_members',
            field=models.ManyToManyField(related_name='services', through='hotel_app.StaffService', to='hotel_app.Staff', verbose_name='Обслуживающий персонал'),
        ),
    ]
