# Generated by Django 3.2.19 on 2025-11-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_auto_20251129_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffservice_set', to='hotel_app.hotelservice', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='staffservice',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffservice_set', to='hotel_app.staff', verbose_name='Сотрудник'),
        ),
    ]
