site_name: Отчет по лабораторной работе 1
site_author: Архангельская Елизавета
site_url: ''

nav:
  - Home: index.md
  - Задание 1: task_1/index.md
  - Задание 2: task_2/index.md
  - Задание 3: task_3/index.md
  - Задание 4: task_4/index.md
  - Задание 5: task_5/index.md

theme:
  name: material