# Generated by Django 6.0.1 on 2026-02-03 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('state_number', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id_owner', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Автовладелец',
                'verbose_name_plural': 'Автовладельцы',
            },
        ),
        migrations.CreateModel(
            name='DriversLicense',
            fields=[
                ('id_license', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('issue_date', models.DateField()),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='project_first_app.carowner')),
            ],
            options={
                'verbose_name': 'Водительское удостоверение',
                'verbose_name_plural': 'Водительские удостоверения',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id_owner_car', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='project_first_app.car')),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='project_first_app.carowner')),
            ],
            options={
                'verbose_name': 'Владение',
                'verbose_name_plural': 'Владения',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(related_name='owned_cars', through='project_first_app.Ownership', through_fields=('id_car', 'id_owner'), to='project_first_app.carowner'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.UniqueConstraint(fields=('id_owner', 'id_car', 'start_date'), name='unique_ownership'),
        ),
    ]
