"""init

Revision ID: 950062242db2
Revises: 
Create Date: 2025-12-15 06:04:07.272713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950062242db2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('breed_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('avg_eggs_per_month', sa.Integer(), nullable=False),
    sa.Column('avg_weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recommended_diet_no', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('breed_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('diet',
    sa.Column('diet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diet_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('diet_id'),
    sa.UniqueConstraint('diet_no')
    )
    op.create_table('employee',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passport', sa.String(length=20), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contract_no', sa.String(length=50), nullable=False),
    sa.Column('fire_date', sa.Date(), nullable=True),
    sa.Column('fire_reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EMPLOYEE', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('workshop',
    sa.Column('workshop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('workshop_id'),
    sa.UniqueConstraint('workshop_no')
    )
    op.create_table('breed_diet_season',
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('diet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.breed_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.diet_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('breed_id', 'season'),
    sa.UniqueConstraint('breed_id', 'season', name='uq_breed_season_one_diet')
    )
    op.create_table('cage',
    sa.Column('cage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('cage_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.workshop_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cage_id'),
    sa.UniqueConstraint('workshop_id', 'row_no', 'cage_no', name='uq_cage_workshop_row_cage')
    )
    op.create_table('chicken',
    sa.Column('chicken_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('cage_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('eggs_per_month', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.breed_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cage_id'], ['cage.cage_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('chicken_id')
    )
    op.create_table('employee_cage',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('cage_id', sa.Integer(), nullable=False),
    sa.Column('assigned_from', sa.Date(), nullable=False),
    sa.Column('assigned_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cage_id'], ['cage.cage_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'cage_id', 'assigned_from'),
    sa.UniqueConstraint('employee_id', 'cage_id', 'assigned_from', name='uq_employee_cage_from')
    )
    op.create_table('chicken_move',
    sa.Column('move_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chicken_id', sa.Integer(), nullable=False),
    sa.Column('from_cage_id', sa.Integer(), nullable=True),
    sa.Column('to_cage_id', sa.Integer(), nullable=False),
    sa.Column('moved_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['chicken_id'], ['chicken.chicken_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_cage_id'], ['cage.cage_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_cage_id'], ['cage.cage_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('move_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chicken_move')
    op.drop_table('employee_cage')
    op.drop_table('chicken')
    op.drop_table('cage')
    op.drop_table('breed_diet_season')
    op.drop_table('workshop')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('employee')
    op.drop_table('diet')
    op.drop_table('breed')
    # ### end Alembic commands ###
