# Generated by Django 4.2.27 on 2025-12-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=15, verbose_name='Гос. номер')),
                ('brand', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Автовладелец',
                'verbose_name_plural': 'Автовладельцы',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='project_first_app.car', verbose_name='Автомобиль')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='project_first_app.carowner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Владение',
                'verbose_name_plural': 'Владения',
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10, verbose_name='Номер удостоверения')),
                ('license_type', models.CharField(max_length=10, verbose_name='Тип')),
                ('issue_date', models.DateTimeField(verbose_name='Дата выдачи')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='project_first_app.carowner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Водительское удостоверение',
                'verbose_name_plural': 'Водительские удостоверения',
            },
        ),
    ]
