# Generated by Django 5.2.8 on 2025-11-17 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Residents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(max_length=30, verbose_name="Номер паспорта"),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                ("surname", models.CharField(max_length=30, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(max_length=30, verbose_name="Отчество"),
                ),
                ("city", models.CharField(max_length=40, verbose_name="Город")),
            ],
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.IntegerField(verbose_name="Номер комнаты")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Номер телефона"
                    ),
                ),
                ("floor", models.IntegerField(verbose_name="Этаж")),
            ],
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("1", "1-местный"),
                            ("2", "2-местный"),
                            ("3", "3-местный"),
                        ],
                        max_length=1,
                        verbose_name="Тип номера",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
            ],
        ),
        migrations.CreateModel(
            name="Workers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                ("surname", models.CharField(max_length=30, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(max_length=30, verbose_name="Отчество"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата заезда"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата выезда"),
                ),
                (
                    "residents",
                    models.ManyToManyField(
                        related_name="reservations", to="hotel_app.residents"
                    ),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        related_name="reservations", to="hotel_app.rooms"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rooms",
            name="id_room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel_app.roomtype",
                verbose_name="Номер отеля",
            ),
        ),
        migrations.CreateModel(
            name="CleaningInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_day",
                    models.CharField(
                        choices=[
                            ("mon", "monday"),
                            ("tue", "tuesday"),
                            ("wed", "wednesday"),
                            ("thu", "thursday"),
                            ("fri", "friday"),
                            ("sat", "saturday"),
                            ("sun", "sunday"),
                        ],
                        max_length=3,
                        verbose_name="День недели",
                    ),
                ),
                ("floor", models.IntegerField(verbose_name="Этаж")),
                (
                    "id_worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaning_information",
                        to="hotel_app.workers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cleaning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата уборки")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleanings",
                        to="hotel_app.rooms",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleanings",
                        to="hotel_app.workers",
                    ),
                ),
            ],
        ),
    ]
