# Generated by Django 5.2.8 on 2025-12-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cleaning",
            old_name="date",
            new_name="cleaning_date",
        ),
    ]
