# Generated by Django 5.2.8 on 2025-12-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0002_rename_date_cleaning_cleaning_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="workers",
            name="is_employed",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Трудоустроен"
            ),
        ),
    ]
