# Generated by Django 5.2.8 on 2025-12-21 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0003_workers_is_employed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rooms",
            name="id_room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="hotel_app.roomtype",
                verbose_name="Номер отеля",
            ),
        ),
    ]
