# Generated by Django 6.0 on 2025-12-23 14:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Автогонка',
                'verbose_name_plural': 'Автогонки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('car_description', models.CharField(blank=True, max_length=300, verbose_name='Описание автомобиля')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('driver_class', models.CharField(choices=[('A', 'Класс A'), ('B', 'Класс B'), ('C', 'Класс C')], default='C', max_length=1, verbose_name='Класс водителя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='racing.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Профиль водителя',
                'verbose_name_plural': 'Профили водителей',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Квалификация, Финал', max_length=100, verbose_name='Название заезда')),
                ('start_time', models.DateTimeField(verbose_name='Время старта')),
                ('laps', models.PositiveSmallIntegerField(default=1, verbose_name='Количество кругов')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'В процессе'), ('finished', 'Завершен'), ('cancelled', 'Отменен')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('info', models.CharField(blank=True, max_length=300, verbose_name='Дополнительная информация')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='racing.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Заезд',
                'verbose_name_plural': 'Заезды',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_date', models.DateField(verbose_name='Дата заезда')),
                ('kind', models.CharField(choices=[('cooperation', 'Вопрос о сотрудничестве'), ('race', 'Вопрос о гонках'), ('other', 'Иное')], max_length=20, verbose_name='Тип комментария')),
                ('rating', models.PositiveSmallIntegerField(help_text='От 1 до 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='racing.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeatResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_time_seconds', models.DecimalField(blank=True, decimal_places=3, help_text='Время прохождения дистанции в секундах, например: 125.456', max_digits=8, null=True, verbose_name='Время финиша (сек)')),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='Место в заезде (1, 2, 3...)', null=True, verbose_name='Позиция')),
                ('status', models.CharField(choices=[('finished', 'Финишировал'), ('dnf', 'Не финишировал (DNF)'), ('dsq', 'Дисквалифицирован (DSQ)'), ('dns', 'Не стартовал (DNS)')], default='finished', max_length=20, verbose_name='Статус')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Примечания')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_results', to='racing.driverprofile', verbose_name='Водитель')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='racing.heat', verbose_name='Заезд')),
            ],
            options={
                'verbose_name': 'Результат заезда',
                'verbose_name_plural': 'Результаты заездов',
                'ordering': ['heat', 'position'],
                'constraints': [models.UniqueConstraint(fields=('heat', 'driver'), name='unique_heat_driver_result')],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('car_number', models.PositiveSmallIntegerField(blank=True, help_text='Гоночный номер для этой гонки', null=True, verbose_name='Номер машины')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='racing.driverprofile', verbose_name='Водитель')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='racing.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('driver', 'race'), name='unique_driver_race_registration')],
            },
        ),
    ]
