# Generated by Django 5.2.7 on 2025-11-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_alter_owner_managers_owner_date_joined_owner_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='home_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='surname',
        ),
        migrations.AlterField(
            model_name='owner',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='owner',
            table=None,
        ),
    ]
