# Generated by Django 5.2.7 on 2025-10-19 21:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=200, verbose_name="Model Name"),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=100, verbose_name="Manufacturer"),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                (
                    "engine_type",
                    models.CharField(max_length=100, verbose_name="Engine Type"),
                ),
                ("horsepower", models.IntegerField(verbose_name="Horsepower (HP)")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "ordering": ["-year", "model_name"],
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Race Name")),
                ("location", models.CharField(max_length=200, verbose_name="Location")),
                (
                    "track_length",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Track Length (km)"
                    ),
                ),
                ("total_laps", models.IntegerField(verbose_name="Total Laps")),
                ("date", models.DateTimeField(verbose_name="Race Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Race",
                "verbose_name_plural": "Races",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Team Name"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("founded_year", models.IntegerField(verbose_name="Founded Year")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Full Name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("professional", "Professional"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Experience Level",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drivers",
                        to="racing.car",
                        verbose_name="Car",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participants",
                        to="racing.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("cooperation", "Cooperation Issue"),
                            ("track", "Track Condition"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Comment Type",
                    ),
                ),
                ("text", models.TextField(verbose_name="Comment Text")),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Rating (1-10)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="racing.race",
                        verbose_name="Race",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RaceParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Final Position"
                    ),
                ),
                (
                    "finish_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Finish Time"
                    ),
                ),
                (
                    "best_lap_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Best Lap Time"
                    ),
                ),
                ("points", models.IntegerField(default=0, verbose_name="Points")),
                (
                    "dnf",
                    models.BooleanField(default=False, verbose_name="Did Not Finish"),
                ),
                (
                    "dnf_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="DNF Reason"
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_entries",
                        to="racing.participant",
                        verbose_name="Participant",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="racing.race",
                        verbose_name="Race",
                    ),
                ),
            ],
            options={
                "verbose_name": "Race Participant",
                "verbose_name_plural": "Race Participants",
                "ordering": ["race", "position"],
                "unique_together": {("race", "participant")},
            },
        ),
    ]
