# Generated by Django 5.2.6 on 2025-12-01 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=50, verbose_name="Производитель"),
                ),
                ("model", models.CharField(max_length=50, verbose_name="Модель")),
                (
                    "serial_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Серийный номер"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hobby", "Любительский"),
                            ("commercial", "Коммерческий"),
                            ("pro", "Профессиональный"),
                        ],
                        default="commercial",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("pending", "Требуется проверка"),
                            ("archived", "Архивирован"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата регистрации дрона"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(blank=True, null=True, verbose_name="Вес"),
                ),
                (
                    "length",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Длина"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ширина"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Высока"
                    ),
                ),
                (
                    "max_speed",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Максимальная скорость"
                    ),
                ),
                (
                    "max_flight_distance",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальная дистанция полёта",
                    ),
                ),
                ("has_camera", models.BooleanField(verbose_name="Наличие камеры")),
            ],
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("certificate", "Сертификат соответствия"),
                            ("insurance", "Страховой полис"),
                            ("photo", "Фото дрона"),
                            ("license", "Лицензия/разрешение"),
                            ("other", "Прочее"),
                        ],
                        max_length=20,
                        verbose_name="Тип документа",
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="URL файла")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время загрузки"
                    ),
                ),
                (
                    "drone_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drones.drones",
                        verbose_name="ID дрона",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Дата и время начала полёта"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(verbose_name="Дата и время конца полёта"),
                ),
                (
                    "location",
                    models.CharField(max_length=50, verbose_name="Регион полёта"),
                ),
                (
                    "purpose",
                    models.CharField(max_length=255, verbose_name="Причина полёта"),
                ),
                (
                    "distance",
                    models.PositiveIntegerField(verbose_name="Дистанция в км"),
                ),
                (
                    "battery_usage",
                    models.FloatField(verbose_name="Использованная батарея в %"),
                ),
                ("notes", models.TextField(null=True, verbose_name="Заметки")),
                (
                    "drone_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drones.drones",
                        verbose_name="ID дрона",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Дата и время лога")),
                ("latitude", models.FloatField(verbose_name="Координаты высоты")),
                ("longtitude", models.FloatField(verbose_name="Координаты ширины")),
                ("altitude", models.FloatField(verbose_name="Высота полёта")),
                ("battery", models.FloatField(verbose_name="Заряд батареи в %")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
                (
                    "flight_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drones.flights"
                    ),
                ),
            ],
        ),
    ]
