# Generated by Django 5.2.6 on 2025-12-01 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="drone_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="drones.drones",
                verbose_name="ID дрона",
            ),
        ),
        migrations.AlterField(
            model_name="flightlogs",
            name="flight_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="drones.flights",
            ),
        ),
        migrations.AlterField(
            model_name="flights",
            name="drone_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="drones.drones",
                verbose_name="ID дрона",
            ),
        ),
        migrations.AlterField(
            model_name="flights",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Заметки"),
        ),
    ]
