# Generated by Django 5.2.6 on 2025-11-03 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="seat_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Забронировано"),
                    ("cancelled", "Отменено"),
                    ("checked_in", "Регистрация пройдена"),
                ],
                default="reserved",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="ticket_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("flight", "seat_number"), name="unique_flight_seat"
            ),
        ),
    ]
