# Generated by Django 5.1.1 on 2025-11-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=64, verbose_name='Отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Библиотекарь',
                'verbose_name_plural': 'Библиотекари',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_card', models.CharField(max_length=64, unique=True, verbose_name='Номер читательского билета')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=64, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ReadingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер зала')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('room_type', models.CharField(choices=[('small', 'Малый зал'), ('medium', 'Средний зал'), ('large', 'Большой зал')], max_length=10, verbose_name='Тип зала')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость (мест)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена/час')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Читальный зал',
                'verbose_name_plural': 'Читальные залы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_from', models.DateTimeField(verbose_name='Время начала бронирования')),
                ('reserved_to', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания бронирования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reading_room.reader', verbose_name='Читатель')),
                ('reading_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reading_room.readingroom', verbose_name='Читальный зал')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-reserved_from'],
                'indexes': [models.Index(fields=['reading_room', 'reserved_from', 'reserved_to'], name='reading_roo_reading_d88d28_idx'), models.Index(fields=['reader', 'reserved_from', 'reserved_to'], name='reading_roo_reader__19653c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Пн'), (2, 'Вт'), (3, 'Ср'), (4, 'Чт'), (5, 'Пт'), (6, 'Сб'), (7, 'Вс')], verbose_name='День недели')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reading_room.librarian', verbose_name='Библиотекарь')),
            ],
            options={
                'verbose_name': 'Расписание библиотекаря',
                'verbose_name_plural': 'Расписания библиотекарей',
                'ordering': ['librarian_id', 'weekday', 'floor'],
                'unique_together': {('librarian', 'weekday', 'floor')},
            },
        ),
    ]
