# Generated by Django 5.2.8 on 2025-12-07 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.ManyToManyField(to='assignments.subject', verbose_name='Преподаваемые предметы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Текст задания')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('due_date', models.DateTimeField(verbose_name='Срок сдачи')),
                ('penalty_info', models.TextField(blank=True, null=True, verbose_name='Информация о штрафах')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
                ('text', models.TextField(verbose_name='Текст решения')),
                ('grade', models.PositiveSmallIntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Оценка')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выставления оценки')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.homework', verbose_name='Домашнее задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Работа студента',
                'verbose_name_plural': 'Работы студентов',
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
