# Generated by Django 5.2.11 on 2026-02-15 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='Дата выезда')),
                ('is_out', models.BooleanField(default=False, verbose_name='Выселился')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='HotelAPI.client', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='HotelAPI.room', verbose_name='Номер')),
            ],
        ),
    ]
