# Generated by Django 5.2.11 on 2026-02-15 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelAPI', '0002_remove_client_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='check_in_date',
            field=models.DateField(default='2026-02-13', verbose_name='Дата заезда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='check_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата уезда'),
        ),
        migrations.AddField(
            model_name='client',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='HotelAPI.room', verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_number',
            field=models.CharField(max_length=20, verbose_name='Номер паспорта'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('passport_number', 'check_in_date')},
        ),
        migrations.DeleteModel(
            name='Stay',
        ),
    ]
