# Generated by Django 5.2.8 on 2025-12-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry_farm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cage',
            name='employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='cages',
            field=models.ManyToManyField(related_name='employees', through='poultry_farm_app.EmployeeCage', to='poultry_farm_app.cage', verbose_name='История закрепления'),
        ),
        migrations.AlterField(
            model_name='breeddiet',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_diets', to='poultry_farm_app.breed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='breeddiet',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_breeds', to='poultry_farm_app.diet', verbose_name='Диета'),
        ),
        migrations.AlterField(
            model_name='employeecage',
            name='cage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_cages', to='poultry_farm_app.cage', verbose_name='Клетка'),
        ),
        migrations.AlterField(
            model_name='employeecage',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_cages', to='poultry_farm_app.employee', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='hencage',
            name='cage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cage_hens', to='poultry_farm_app.cage', verbose_name='Клетка'),
        ),
        migrations.AlterField(
            model_name='hencage',
            name='hen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hen_cages', to='poultry_farm_app.hen', verbose_name='Курица'),
        ),
    ]
