# Generated by Django 5.2.8 on 2025-12-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Nissan', 'Nissan'), ('Hyundai', 'Hyundai'), ('Mercedes', 'Mercedes-Benz'), ('BMW', 'BMW'), ('Audi', 'Audi')], max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('state_number', models.CharField(max_length=20, unique=True, verbose_name='номер машины')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='Номер водительского удостоверения')),
                ('license_type', models.CharField(choices=[('A', 'Мотоциклы'), ('B', 'Легковые автомобили'), ('C', 'Грузовые автомобили'), ('D', 'Автобусы')], max_length=1, verbose_name='тип категории вождения')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverlicense', to='cars.carowner', verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала прав')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания прав')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='cars.car', verbose_name='автомобиль')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='cars.carowner', verbose_name='Владелец')),
            ],
        ),
    ]
