# Generated by Django 3.2.25 on 2025-12-14 14:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название гонки')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('description', models.TextField(verbose_name='Описание гонки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Автогонка',
                'verbose_name_plural': 'Автогонки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('team_name', models.CharField(max_length=200, verbose_name='Название команды')),
                ('car_description', models.TextField(verbose_name='Описание автомобиля')),
                ('racer_description', models.TextField(verbose_name='Описание участника')),
                ('experience', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('professional', 'Профессионал')], max_length=20, verbose_name='Опыт')),
                ('racer_class', models.CharField(choices=[('formula1', 'Формула-1'), ('formula2', 'Формула-2'), ('formula3', 'Формула-3'), ('rally', 'Ралли'), ('endurance', 'Выносливость'), ('other', 'Другое')], max_length=20, verbose_name='Класс участника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Гонщик',
                'verbose_name_plural': 'Гонщики',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateField(verbose_name='Дата заезда')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('comment_type', models.CharField(choices=[('cooperation', 'Вопрос о сотрудничестве'), ('race_question', 'Вопрос о гонках'), ('other', 'Иное')], max_length=20, verbose_name='Тип комментария')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='racing.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('race_time', models.TimeField(blank=True, null=True, verbose_name='Время заезда')),
                ('result', models.CharField(blank=True, max_length=100, verbose_name='Результат')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Позиция')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.race', verbose_name='Гонка')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.racer', verbose_name='Гонщик')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'ordering': ['-registration_date'],
                'unique_together': {('racer', 'race')},
            },
        ),
    ]
