# Generated by Django 5.2.8 on 2025-11-28 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('colour', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car_owner',
            },
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_license', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('date_issue', models.DateField()),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_drf_app.carowner')),
            ],
            options={
                'db_table': 'driving_license',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('final_date', models.DateField(blank=True, null=True)),
                ('id_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simple_drf_app.car')),
                ('id_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simple_drf_app.carowner')),
            ],
            options={
                'db_table': 'ownership',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(through='simple_drf_app.Ownership', to='simple_drf_app.carowner'),
        ),
    ]
