services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "warriors"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/15/data

volumes:
  postgres_data:
