# Generated by Django 5.2.7 on 2025-11-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warriors_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warrior",
            name="profession",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warriors",
                to="warriors_app.profession",
                verbose_name="Профессия",
            ),
        ),
        migrations.AlterField(
            model_name="warrior",
            name="skill",
            field=models.ManyToManyField(
                related_name="warrior_skills",
                through="warriors_app.SkillOfWarrior",
                to="warriors_app.skill",
                verbose_name="Умения",
            ),
        ),
    ]
