# Generated by Django 4.2.25 on 2025-10-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID автомобиля')),
                ('state_number', models.IntegerField(verbose_name='Гос. удостоверение')),
                ('brand', models.CharField(max_length=30, verbose_name='Марка')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('color', models.CharField(blank=True, choices=[('RED', 'Красный'), ('BLUE', 'Синий'), ('GREEN', 'Зеленый'), ('BLACK', 'Черный'), ('WHITE', 'Белый'), ('SILVER', 'Серебристый'), ('GRAY', 'Серый')], max_length=30, null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
                'db_table': 'owner',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала владения')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания владения')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automobiles.car', verbose_name='Автомобиль')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automobiles.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Владение',
                'verbose_name_plural': 'Владения',
                'db_table': 'ownership',
                'unique_together': {('owner', 'car')},
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID удостоверения')),
                ('license_number', models.CharField(max_length=10, verbose_name='Номер удостоверения')),
                ('license_type', models.CharField(choices=[('A', 'Категория A'), ('B', 'Категория B'), ('C', 'Категория C'), ('D', 'Категория D'), ('E', 'Категория E')], max_length=10, verbose_name='Тип удостоверения')),
                ('issue_date', models.DateTimeField(verbose_name='Дата выдачи')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobiles.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Водительское удостоверение',
                'verbose_name_plural': 'Водительские удостоверения',
                'db_table': 'driver_license',
                'unique_together': {('license_number',)},
            },
        ),
    ]
