# Generated by Django 4.2.25 on 2025-10-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownership',
            options={'ordering': ['-start_date'], 'verbose_name': 'Владение', 'verbose_name_plural': 'Владения'},
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания срока действия'),
        ),
        migrations.AddField(
            model_name='owner',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='owner',
            name='cars',
            field=models.ManyToManyField(related_name='owners', through='automobiles.Ownership', to='automobiles.car', verbose_name='Автомобили'),
        ),
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, choices=[('RED', 'Красный'), ('BLUE', 'Синий'), ('GREEN', 'Зеленый'), ('BLACK', 'Черный'), ('WHITE', 'Белый'), ('SILVER', 'Серебристый'), ('GRAY', 'Серый'), ('YELLOW', 'Желтый'), ('BROWN', 'Коричневый')], max_length=30, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='license_type',
            field=models.CharField(choices=[('A', 'Категория A - Мотоциклы'), ('B', 'Категория B - Легковые автомобили'), ('C', 'Категория C - Грузовые автомобили'), ('D', 'Категория D - Автобусы'), ('E', 'Категория E - Составы ТС'), ('BE', 'Категория BE - Легковые с прицепом'), ('CE', 'Категория CE - Грузовые с прицепом'), ('DE', 'Категория DE - Автобусы с прицепом')], max_length=10, verbose_name='Тип удостоверения'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='automobiles.owner', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='automobiles.car', verbose_name='Автомобиль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='automobiles.owner', verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('owner', 'car', 'start_date')},
        ),
    ]
