# Generated by Django 4.2.25 on 2025-10-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0002_alter_ownership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Домашний адрес'),
        ),
        migrations.AddField(
            model_name='owner',
            name='nationality',
            field=models.CharField(blank=True, choices=[('RU', 'Российская Федерация'), ('BY', 'Республика Беларусь'), ('KZ', 'Республика Казахстан'), ('UA', 'Украина'), ('OTHER', 'Другая')], max_length=10, null=True, verbose_name='Национальность'),
        ),
        migrations.AddField(
            model_name='owner',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта'),
        ),
    ]
