# Generated by Django 4.2.25 on 2025-10-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0003_owner_address_owner_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта'),
        ),
    ]
