# Generated by Django 3.2 on 2025-12-28 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwboard', '0002_auto_20251228_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('experience', models.IntegerField(default=0, verbose_name='Стаж (лет)')),
                ('teacher_code', models.CharField(max_length=20, unique=True, verbose_name='Код преподавателя')),
                ('is_class_teacher', models.BooleanField(default=False, verbose_name='Классный руководитель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль преподавателя',
                'verbose_name_plural': 'Профили преподавателей',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10, verbose_name='Класс')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон родителей')),
                ('admission_year', models.IntegerField(verbose_name='Год поступления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль ученика',
                'verbose_name_plural': 'Профили учеников',
            },
        ),
    ]
