# Generated by Django 3.2 on 2026-01-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwboard', '0003_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
