# Generated by Django 3.2 on 2026-01-17 20:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwboard', '0004_auto_20260114_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('due_date', models.DateField(verbose_name='Срок выполнения')),
                ('text', models.TextField(verbose_name='Текст задания')),
                ('penalty_info', models.TextField(blank=True, verbose_name='Информация о штрафах')),
                ('for_class', models.CharField(max_length=10, verbose_name='Для класса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('teachers', models.ManyToManyField(related_name='subjects', to='hwboard.TeacherProfile', verbose_name='Преподаватели')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(verbose_name='Текст сдачи')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Время сдачи')),
                ('status', models.CharField(choices=[('submitted', 'Сдано'), ('late', 'Сдано с опозданием')], default='submitted', max_length=20)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwboard.homework', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwboard.studentprofile', verbose_name='Ученик')),
            ],
            options={
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwboard.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwboard.teacherprofile', verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('teacher_feedback', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hwboard.homeworksubmission', verbose_name='Сдача')),
            ],
        ),
    ]
