# Generated by Django 4.2.26 on 2025-12-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0002_insurancepolicy_ownercontact_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
