# Generated by Django 4.2.26 on 2025-12-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0003_owner_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlicense',
            name='license_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
