# Generated by Django 3.2 on 2025-11-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='carowner',
            old_name='owner_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='drivinglicense',
            old_name='license_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='ownership_id',
            new_name='id',
        ),
    ]
