# Generated by Django 5.2.6 on 2025-09-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирован'), ('in_flight', 'В полёте'), ('arrived', 'Прибыл'), ('delayed', 'Задержан'), ('cancelled', 'Отменён')], default='scheduled', max_length=20),
        ),
    ]
