# Generated by Django 5.2.7 on 2025-10-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carowner",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="date_of_issue",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="start_date",
            field=models.DateField(),
        ),
    ]
