# Generated by Django 5.2.7 on 2025-10-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0002_alter_carowner_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownership",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
