# Generated by Django 5.2.7 on 2025-10-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0003_alter_ownership_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="owners",
            field=models.ManyToManyField(
                through="project_first_app.Ownership", to="project_first_app.carowner"
            ),
        ),
        migrations.AddField(
            model_name="carowner",
            name="cars",
            field=models.ManyToManyField(
                through="project_first_app.Ownership", to="project_first_app.car"
            ),
        ),
    ]
