services:
  db:
    container_name: postgres_db
    image: postgres:16
    environment:
      POSTGRES_DB: hwboard_db
      POSTGRES_USER: hwboard_user
      POSTGRES_PASSWORD: q
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # web:
  #   build: .
  #   command: python manage.py runserver 127.0.0.1:8000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgres://hwboard_user:hwboard_password@db:5432/hwboard_db

volumes:
  postgres_data:
