# Generated by Django 6.0.2 on 2026-02-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='library_card_id',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Номер читательского билета'),
        ),
    ]
