# Generated by Django 6.0.2 on 2026-02-04 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_reader_library_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='last_registration_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата последней регистрации/перерегистрации'),
        ),
    ]
