# Generated by Django 6.0.2 on 2026-02-04 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_reader_last_registration_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrecord',
            name='issued_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата выдачи'),
        ),
    ]
