# Generated by Django 5.2.8 on 2025-11-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('plate_number', models.CharField(max_length=16, unique=True, verbose_name='Гос. номер')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Номер удостоверения')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='garage.owner', verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала владения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания владения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='garage.car', verbose_name='Автомобиль')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='garage.owner', verbose_name='Владелец')),
            ],
        ),
    ]
