site_name: "Отчёт по лабораторным работам"
site_description: "Все лабораторные работы по предмету Web Development 2025-2026"
site_author: "Твой Имя"
site_url: "https://dfgion.github.io/TonikX-ITMO_ICT_WebDevelopment_2025-2026/"

theme:
  name: material 
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Fira Code'
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.annotate
    - toc.integrate

nav:
  - Главная: index.md
  - Задание 1: task1/index.md
  - Задание 2: task2/index.md
  - Задание 3: task3/index.md
  - Задание 4: task4/index.md
  - Задание 5: task5/index.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true

repo_name: "dfgion/TonikX-ITMO_ICT_WebDevelopment_2025-2026"
repo_url: "https://github.com/dfgion/TonikX-ITMO_ICT_WebDevelopment_2025-2026"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dfgion/TonikX-ITMO_ICT_WebDevelopment_2025-2026
