# Generated by Django 5.2 on 2025-12-17 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='DepositType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование вклада')),
                ('description', models.TextField(verbose_name='Описание вклада')),
                ('min_term', models.IntegerField(verbose_name='Минимальный срок (мес)')),
                ('min_sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Минимальная сумма')),
                ('term', models.IntegerField(verbose_name='Срок')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процентная ставка')),
            ],
            options={
                'verbose_name': 'Тип вклада',
                'verbose_name_plural': 'Типы вкладов',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('dob', models.DateField(verbose_name='Дата рождения')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('passport_data', models.TextField(verbose_name='Паспортные данные')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Оклад')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('loan_type', models.CharField(max_length=100, verbose_name='Тип')),
                ('term', models.IntegerField(verbose_name='Срок')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процентная ставка')),
            ],
            options={
                'verbose_name': 'Тип кредита',
                'verbose_name_plural': 'Типы кредитов',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Оклад')),
                ('vacancies_count', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('contract_data', models.TextField(verbose_name='Данные договора')),
                ('deposit_data', models.TextField(blank=True, verbose_name='Данные вклада')),
                ('deposit_sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма вклада')),
                ('return_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма возврата')),
                ('deposit_date', models.DateField(verbose_name='Дата вклада')),
                ('return_date', models.DateField(verbose_name='Дата возврата')),
                ('fact_return_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата возврата')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.currency', verbose_name='Код валюты')),
                ('deposit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.deposittype', verbose_name='Тип вклада')),
            ],
            options={
                'verbose_name': 'Вклад',
                'verbose_name_plural': 'Вклады',
            },
        ),
        migrations.CreateModel(
            name='AccrualSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата начисления')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма начисления')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='banking.deposit', verbose_name='Вклад')),
            ],
            options={
                'verbose_name': 'График начислений',
                'verbose_name_plural': 'Графики начислений',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Стоимость покупки')),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Стоимость продажи')),
                ('multiplicity', models.IntegerField(default=1, verbose_name='Кратность')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.currency', verbose_name='Код валюты')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='OccupiedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата вступления')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Занимаемая должность',
                'verbose_name_plural': 'Занимаемые должности',
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.occupiedposition', verbose_name='Оформил сотрудник'),
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10, verbose_name='Серия')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('date_issue', models.DateField(verbose_name='Дата выдачи')),
                ('issuer', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('fio', models.CharField(blank=True, max_length=255, verbose_name='ФИО в паспорте')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='banking.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('contract_data', models.TextField(verbose_name='Данные договора')),
                ('loan_data', models.TextField(blank=True, verbose_name='Данные кредита')),
                ('trusted_person', models.CharField(blank=True, max_length=255, verbose_name='Доверенное лицо')),
                ('date_issue', models.DateField(verbose_name='Дата кредита')),
                ('sum_credit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма кредита')),
                ('payout_count', models.IntegerField(verbose_name='Число выплат')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ежемесячная сумма')),
                ('close_date', models.DateField(verbose_name='Дата закрытия')),
                ('fact_close_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата закрытия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.currency', verbose_name='Код валюты')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.loantype', verbose_name='Тип кредита')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.occupiedposition', verbose_name='Оформил сотрудник')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.passport', verbose_name='Паспорт')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.passport', verbose_name='Паспорт'),
        ),
        migrations.CreateModel(
            name='PayoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payout', models.DateField(verbose_name='Дата выплаты')),
                ('sum_payout', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма выплаты')),
                ('sum_interest', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма выплаты по процентам')),
                ('remainder', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Остаток')),
                ('fact_date_payout', models.DateField(blank=True, null=True, verbose_name='Дата фактической выплаты')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='banking.loan', verbose_name='Кредит')),
            ],
            options={
                'verbose_name': 'График выплат',
                'verbose_name_plural': 'Графики выплат',
            },
        ),
    ]
