# Generated by Django 5.2 on 2025-12-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Клиента')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id_credit', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Кредита')),
                ('contract_data', models.CharField(max_length=255, verbose_name='Данные договора')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('credit_date', models.DateField(verbose_name='Дата кредита')),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма кредита')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ежемесячная сумма')),
                ('payment_count', models.IntegerField(verbose_name='Число выплаты')),
                ('authorized_person', models.CharField(max_length=255, verbose_name='Доверенное лицо')),
                ('closing_date', models.DateField(verbose_name='Дата закрытия')),
                ('actual_closing_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата закрытия')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
            },
        ),
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id_credit_type', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Типа кредита')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('term', models.IntegerField(verbose_name='Срок')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процентная ставка')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Остаток')),
            ],
            options={
                'verbose_name': 'Тип кредита',
                'verbose_name_plural': 'Типы кредитов',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='DepositType',
            fields=[
                ('id_deposit_type', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Типа вклада')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование вклада')),
                ('description', models.TextField(verbose_name='Описание вклада')),
                ('min_term', models.IntegerField(verbose_name='Минимальный срок вклада')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Минимальная сумма вклада')),
                ('term', models.IntegerField(verbose_name='Срок (в днях/месяцах)')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процентная ставка')),
            ],
            options={
                'verbose_name': 'Тип вклада',
                'verbose_name_plural': 'Типы вкладов',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Сотрудника')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('passport_data', models.CharField(max_length=50, verbose_name='Паспортные данные')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оклад')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id_position', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Должности')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оклад')),
                ('vacancies_count', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='CreditPaymentSchedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Графика выплат')),
                ('payment_date', models.DateField(verbose_name='Дата выплаты')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма выплаты')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Остаток')),
                ('actual_payment_date', models.DateField(blank=True, null=True, verbose_name='Дата фактической выплаты')),
                ('interest_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма выплаты по процентам')),
                ('number', models.IntegerField(verbose_name='Номер выплаты')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='banking.credit', verbose_name='ID Кредита')),
            ],
            options={
                'verbose_name': 'График выплат по кредиту',
                'verbose_name_plural': 'Графики выплат по кредиту',
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.credittype', verbose_name='Тип кредита'),
        ),
        migrations.AddField(
            model_name='credit',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.currency', verbose_name='Код валюты'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id_deposit', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Вклада')),
                ('contract_data', models.CharField(max_length=255, verbose_name='Данные договора')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('deposit_date', models.DateField(verbose_name='Дата вклада')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма вклада')),
                ('return_date', models.DateField(verbose_name='Дата возврата')),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма возврата')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата возврата')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.currency', verbose_name='Код валюты')),
                ('deposit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.deposittype', verbose_name='Тип вклада')),
            ],
            options={
                'verbose_name': 'Вклад',
                'verbose_name_plural': 'Вклады',
            },
        ),
        migrations.CreateModel(
            name='DepositSchedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Графика начислений')),
                ('charge_date', models.DateField(verbose_name='Дата начисления')),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма начисления')),
                ('number', models.IntegerField(verbose_name='Номер начисления')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='banking.deposit', verbose_name='ID Вклада')),
            ],
            options={
                'verbose_name': 'График начислений',
                'verbose_name_plural': 'Графики начислений',
            },
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id_employee_position', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Занимаемой должности')),
                ('start_date', models.DateField(verbose_name='Дата вступления в должность')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания должности')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_history', to='banking.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Занимаемая должность',
                'verbose_name_plural': 'Занимаемые должности',
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='employee_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.employeeposition', verbose_name='Занимаемая должность сотрудника'),
        ),
        migrations.AddField(
            model_name='credit',
            name='employee_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.employeeposition', verbose_name='Занимаемая должность сотрудника'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id_rate', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Курса')),
                ('multiplier', models.IntegerField(verbose_name='Кратность')),
                ('purchase_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Стоимость покупки')),
                ('sale_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Стоимость продажи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='banking.currency', verbose_name='Код валюты')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id_passport', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Паспорта')),
                ('series', models.CharField(max_length=4, verbose_name='Серия')),
                ('number', models.CharField(max_length=6, verbose_name='Номер')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('fio_on_passport', models.CharField(max_length=255, verbose_name='ФИО в паспорте')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='banking.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.passport', verbose_name='Паспорт'),
        ),
    ]
