# Generated by Django 4.2.25 on 2025-11-02 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotels", "0002_alter_reservation_options_reservation_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="review",
            name="check_in",
        ),
        migrations.RemoveField(
            model_name="review",
            name="check_out",
        ),
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="stay_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="stay_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
