# Generated by Django 4.2.25 on 2025-11-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_alter_review_options_remove_review_check_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="stars",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
