site_name: School System API
site_description: Документация для серверной части школьной системы
site_url: http://localhost:9000/

theme:
  name: mkdocs


nav:
  - Главная: index.md
  - Модели данных: models.md
  - API эндпоинты: api.md
  - Клиентская часть: frontend.md
  - Отчеты: reports.md
