# Generated by Django 5.2.7 on 2025-10-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hoteluser",
            name="passport_number",
        ),
    ]
