# Generated by Django 5.2.7 on 2025-10-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_remove_hoteluser_passport_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="id_hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotels.hotel"
            ),
        ),
    ]
