# Generated by Django 5.2.7 on 2025-10-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_alter_roomtype_id_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="id_rooms",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotels.roomtype"
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="count",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
