# Generated by Django 5.2.7 on 2025-10-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0004_alter_reservation_id_rooms_roomtype_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="pay_date",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="pay_status",
        ),
    ]
