# Generated by Django 5.2.7 on 2025-10-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0005_remove_reservation_pay_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="id_user",
        ),
    ]
