# Generated by Django 5.2.7 on 2025-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0006_remove_review_id_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="num_of_people",
            field=models.IntegerField(default=0),
        ),
    ]
