# Generated by Django 5.2.7 on 2025-10-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0007_reservation_num_of_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="num_of_people",
            field=models.IntegerField(default=1),
        ),
    ]
