# Generated by Django 5.2.7 on 2025-10-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0008_alter_reservation_num_of_people"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="capacity",
        ),
    ]
