# Generated by Django 5.2.7 on 2025-10-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0009_remove_hotel_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="id_reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="hotels.reservation"
            ),
        ),
    ]
