# Generated by Django 5.2.7 on 2025-11-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код аэропорта (IATA/ICAO)')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('status', models.CharField(help_text='Например: active / closed / maintenance', max_length=20, verbose_name='Статус')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('name', models.CharField(max_length=200, verbose_name='Название аэропорта')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('company_type', models.CharField(choices=[('carrier', 'Авиаперевозчик'), ('airport_owner', 'Владелец аэропорта'), ('ground', 'Наземное обслуживание'), ('other', 'Другое')], max_length=20, verbose_name='Тип компании')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('passport_serial', models.CharField(max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('passport_region', models.CharField(max_length=200, verbose_name='Кем выдан / регион')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='PlaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка / тип самолёта')),
                ('seat_count', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('cruise_speed', models.FloatField(verbose_name='Крейсерская скорость (км/ч)')),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('education', models.CharField(max_length=200, verbose_name='Образование')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Стаж (лет)')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('passport_serial', models.CharField(max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('passport_region', models.CharField(max_length=200, verbose_name='Кем выдан / регион')),
                ('role', models.CharField(max_length=50, verbose_name='Роль (командир, 2й пилот, стюард и т.п.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает в компании')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='Допущен к полётам')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='airport_api.company', verbose_name='Работодатель')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Роль на рейсе (КВС, второй пилот, стюард)')),
                ('medical_check_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата медосмотра')),
                ('medical_status', models.CharField(help_text='Допущен / ограниченно / недопущен', max_length=50, verbose_name='Мед. статус')),
                ('medical_reason', models.TextField(blank=True, verbose_name='Причина ограничения/недопуска')),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='airport_api.crewmember', verbose_name='Член экипажа')),
            ],
            options={
                'verbose_name': 'Экипаж на рейсе',
                'verbose_name_plural': 'Экипажи на рейсах',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, verbose_name='Номер рейса')),
                ('operating_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operated_flights', to='airport_api.company', verbose_name='Эксплуатант (перевозчик)')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='FlightInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('boarding', 'Посадка'), ('departed', 'Вылетел'), ('arrived', 'Прибыл'), ('cancelled', 'Отменён')], default='scheduled', max_length=20, verbose_name='Статус вылета')),
                ('departure_time', models.DateTimeField(verbose_name='Плановое время вылета')),
                ('departure_time_fact', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время вылета')),
                ('arrival_time', models.DateTimeField(verbose_name='Плановое время прилёта')),
                ('arrival_time_fact', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время прилёта')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='airport_api.flight', verbose_name='Рейс')),
            ],
        ),
        migrations.AddField(
            model_name='crewmember',
            name='flights',
            field=models.ManyToManyField(related_name='crew_members', through='airport_api.Crew', to='airport_api.flightinstance', verbose_name='Рейсы'),
        ),
        migrations.AddField(
            model_name='crew',
            name='flight_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='airport_api.flightinstance', verbose_name='Конкретный вылет'),
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20, unique=True, verbose_name='Бортовой номер (рег. номер)')),
                ('status', models.CharField(choices=[('active', 'В строю'), ('maintenance', 'В ремонте/ТО'), ('retired', 'Списан')], default='active', max_length=20, verbose_name='Статус борта')),
                ('flight_hours', models.FloatField(default=0, verbose_name='Налёт (часы)')),
                ('last_technical_service', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего ТО')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='airport_api.company', verbose_name='Владелец борта')),
                ('plane_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='airport_api.planetype', verbose_name='Тип самолёта')),
            ],
        ),
        migrations.AddField(
            model_name='flightinstance',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_instances', to='airport_api.plane', verbose_name='Самолёт'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(verbose_name='Дистанция (км)')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_routes', to='airport_api.airport', verbose_name='Аэропорт вылета')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_routes', to='airport_api.airport', verbose_name='Аэропорт назначения')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airport_api.route', verbose_name='Маршрут'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5, verbose_name='Номер места (например 12A)')),
                ('seat_type', models.CharField(choices=[('economy', 'Эконом'), ('business', 'Бизнес'), ('first', 'Первый')], max_length=20, verbose_name='Класс обслуживания')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Место забронировано')),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='airport_api.flightinstance', verbose_name='Конкретный вылет')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_channel', models.CharField(help_text='Например: online, касса, агент', max_length=50, verbose_name='Канал продажи')),
                ('status', models.CharField(choices=[('booked', 'Бронирован'), ('paid', 'Оплачен'), ('cancelled', 'Отменён'), ('refunded', 'Возврат')], default='booked', max_length=20, verbose_name='Статус билета')),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дополнительные сборы')),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airport_api.flightinstance', verbose_name='Конкретный вылет')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airport_api.passenger', verbose_name='Пассажир')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='airport_api.seat', verbose_name='Место')),
            ],
        ),
        migrations.CreateModel(
            name='TransitStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveSmallIntegerField(verbose_name='Порядок посадки (1,2,3...)')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прилёта')),
                ('departure_time', models.DateTimeField(verbose_name='Время вылета')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transit_stops', to='airport_api.airport', verbose_name='Аэропорт посадки')),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_stops', to='airport_api.flightinstance', verbose_name='Конкретный вылет')),
            ],
            options={
                'verbose_name': 'Транзитная посадка',
                'verbose_name_plural': 'Транзитные посадки',
                'ordering': ['stop_order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='crew',
            unique_together={('crew_member', 'flight_instance')},
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('departure_airport', 'destination_airport'), name='uniq_route_departure_destination'),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_number', 'operating_company')},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('flight_instance', 'seat_number')},
        ),
    ]
