# Generated by Django 6.0 on 2025-12-19 04:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Текст задания')),
                ('issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('due_date', models.DateField(verbose_name='Срок выполнения')),
                ('penalty_info', models.TextField(blank=True, verbose_name='Информация о штрафах')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_app.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(verbose_name='Текст решения')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('feedback', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_app.homework', verbose_name='Задание')),
                ('student', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Сданное задание',
                'verbose_name_plural': 'Сданные задания',
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
