# Generated by Django 5.0 on 2025-09-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="birth_date",
            field=models.DateField(null=True),
        ),
    ]
