# Generated by Django 5.0 on 2025-09-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0003_alter_owner_options_alter_owner_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="owner",
            name="nationality",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="owner",
            name="passport_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="owner",
            name="password",
            field=models.CharField(
                default="user123", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
    ]
