# Generated by Django 4.2.25 on 2025-10-14 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_first_app",
            "0004_alter_owner_address_alter_owner_nationality_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="owners",
            field=models.ManyToManyField(
                related_name="cars",
                through="project_first_app.Ownership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="car",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to="project_first_app.car",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
