# Generated by Django 5.2.7 on 2025-10-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='teacher_first_name',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher_last_name',
        ),
    ]
