# Generated by Django 5.2.7 on 2025-10-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_teacher_first_name_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', '📤 Сдано'), ('graded', '✅ Оценено'), ('late', '⚠️ Сдано с опозданием'), ('not_submitted', '⏳ Не сдано')], default='submitted', max_length=20),
        ),
    ]
