# Generated by Django 3.2 on 2026-01-22 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('automobile_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_number', models.CharField(max_length=15)),
                ('mark', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Автовладелец',
                'verbose_name_plural': 'Автовладельцы',
            },
        ),
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('possession_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('automobile_id', models.ForeignKey(db_column='Id_автомобиля', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_first_app.automobile')),
                ('owner_id', models.ForeignKey(db_column='Id_владельца', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_first_app.owner')),
            ],
            options={
                'verbose_name': 'Владение автомобилем',
                'verbose_name_plural': 'Владения автомобилями',
                'db_table': 'Владение',
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('driver_license_id', models.AutoField(primary_key=True, serialize=False)),
                ('id_number', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('date_of_issue', models.DateField()),
                ('owner_id', models.ForeignKey(db_column='Id_владельца', on_delete=django.db.models.deletion.CASCADE, to='project_first_app.owner')),
            ],
            options={
                'verbose_name': 'Водительское удостоверение',
                'verbose_name_plural': 'Водительские удостоверения',
            },
        ),
    ]
