# Generated by Django 5.2.7 on 2025-10-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id_carOwner', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id_DriverLicense', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=10)),
                ('license_type', models.CharField(max_length=10)),
                ('issue_date', models.DateField()),
                ('id_carOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carowners.carowner')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id_OwnerShip', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carowners.car')),
                ('id_carOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carowners.carowner')),
            ],
        ),
    ]
