# Generated by Django 5.2.8 on 2026-02-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrior',
            name='race',
            field=models.CharField(choices=[('s', 'squire'), ('k', 'knight'), ('m', 'mage')], max_length=1, verbose_name='Раса'),
        ),
    ]
