# Generated by Django 3.2.25 on 2025-12-14 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
            ],
            options={
                'verbose_name': 'Служащий',
                'verbose_name_plural': 'Служащие',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты')),
                ('room_type', models.CharField(choices=[('single', 'Одноместный'), ('double', 'Двухместный'), ('triple', 'Трехместный')], max_length=10, verbose_name='Тип номера')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость за сутки')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Занят')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='Дата заселения')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='Дата выселения')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='hotel.guest', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='hotel.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Проживание',
                'verbose_name_plural': 'Проживания',
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('day_of_week', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=10, verbose_name='День недели')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_schedules', to='hotel.employee', verbose_name='Служащий')),
            ],
            options={
                'verbose_name': 'Расписание уборки',
                'verbose_name_plural': 'Расписания уборки',
                'ordering': ['day_of_week', 'floor'],
                'unique_together': {('employee', 'floor', 'day_of_week')},
            },
        ),
    ]
