# Generated by Django 6.0.1 on 2026-02-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2_first_app', '0002_alter_trip_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(verbose_name='Окончание поездки'),
        ),
    ]
