# Generated by Django 6.0 on 2025-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
