# Generated by Django 6.0 on 2025-12-19 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_visit_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="clinic.visit",
            ),
        ),
    ]
