# Generated by Django 6.0 on 2025-12-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_alter_payment_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="visit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="clinic.visit",
            ),
        ),
    ]
