# Generated by Django 5.2.7 on 2025-11-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Автовладелец',
                'verbose_name_plural': 'Автовладельцы',
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15, verbose_name='Гос. номер')),
                ('make', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['make', 'model', 'plate_number'],
                'indexes': [models.Index(fields=['plate_number'], name='garage_car_plate_n_abeb53_idx'), models.Index(fields=['make', 'model'], name='garage_car_make_f74453_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='garage.car', verbose_name='Автомобиль')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='garage.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Владение',
                'verbose_name_plural': 'Владения',
                'ordering': ['-start_date', 'owner_id', 'car_id'],
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='owners', through='garage.Ownership', to='garage.car', verbose_name='Автомобили'),
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер удостоверения')),
                ('type', models.CharField(max_length=10, verbose_name='Тип')),
                ('issue_date', models.DateTimeField(verbose_name='Дата выдачи')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='garage.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Водительское удостоверение',
                'verbose_name_plural': 'Водительские удостоверения',
                'ordering': ['-issue_date', 'number'],
                'indexes': [models.Index(fields=['number'], name='garage_driv_number_ca0ced_idx')],
            },
        ),
    ]
