# Generated by Django 5.2.8 on 2025-11-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название гонки')),
                ('description', models.TextField(verbose_name='Описание гонки')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Гонка',
                'verbose_name_plural': 'Гонки',
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_time', models.DurationField(blank=True, null=True, verbose_name='Время круга')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('completed_laps', models.PositiveIntegerField(default=0, verbose_name='Пройдено кругов')),
            ],
            options={
                'verbose_name': 'Результат гонки',
                'verbose_name_plural': 'Результаты гонок',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RaceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Регистрация на гонку',
                'verbose_name_plural': 'Регистрации на гонки',
            },
        ),
    ]
