# Generated by Django 5.2.8 on 2025-12-15 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['-date'], 'verbose_name': 'Гонка', 'verbose_name_plural': 'Гонки'},
        ),
        migrations.AlterUniqueTogether(
            name='raceresult',
            unique_together={('race', 'position')},
        ),
    ]
