# Generated by Django 6.0.2 on 2026-02-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('publisher', models.CharField(max_length=200, verbose_name='Издательство')),
                ('publication_year', models.IntegerField(verbose_name='Год издания')),
                ('section', models.CharField(max_length=100, verbose_name='Раздел')),
                ('inventory_code', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('is_in_catalog', models.BooleanField(default=True, verbose_name='В каталоге')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('reader_id', models.AutoField(primary_key=True, serialize=False)),
                ('library_card_id', models.CharField(max_length=50, unique=True, verbose_name='Номер читательского билета')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('education_level', models.CharField(choices=[('primary', 'Начальное'), ('secondary', 'Среднее'), ('higher', 'Высшее'), ('degree', 'Ученая степень')], max_length=20, verbose_name='Образование')),
                ('passport', models.CharField(max_length=50, verbose_name='Номер паспорта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('home_address', models.TextField(verbose_name='Адрес')),
                ('is_active_member', models.BooleanField(default=True, verbose_name='Активный читатель')),
                ('first_registered_at', models.DateField(auto_now_add=True, verbose_name='Дата первой регистрации')),
                ('last_registration_at', models.DateField(auto_now=True, verbose_name='Дата последней регистрации')),
            ],
            options={
                'db_table': 'Reader',
            },
        ),
        migrations.CreateModel(
            name='ReadingHall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('hall_number', models.IntegerField(unique=True, verbose_name='Номер зала')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
            ],
            options={
                'db_table': 'ReadingHall',
            },
        ),
        migrations.CreateModel(
            name='CopyOfBook',
            fields=[
                ('copy_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('availability_status', models.CharField(choices=[('available', 'Доступен'), ('on_loan', 'Выдан'), ('reserved', 'Зарезервирован'), ('decommissioned', 'Списан')], default='available', max_length=20, verbose_name='Статус доступности')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('copy_condition', models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('fair', 'Удовлетворительное'), ('poor', 'Плохое'), ('damaged', 'Поврежден')], default='good', max_length=20, verbose_name='Состояние')),
                ('decommission_date', models.DateField(blank=True, null=True, verbose_name='Дата списания')),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Книга')),
                ('hall_id', models.ForeignKey(db_column='hall_id', on_delete=django.db.models.deletion.PROTECT, to='library_app.readinghall', verbose_name='Зал')),
            ],
            options={
                'db_table': 'CopyOfBook',
            },
        ),
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('issued_at', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('due_date', models.DateField(verbose_name='Срок возврата')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('copy_book_id', models.ForeignKey(db_column='copy_book_id', on_delete=django.db.models.deletion.PROTECT, to='library_app.copyofbook', verbose_name='Экземпляр книги')),
                ('reader_id', models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.PROTECT, to='library_app.reader', verbose_name='Читатель')),
            ],
            options={
                'db_table': 'LoanRecord',
            },
        ),
        migrations.AddField(
            model_name='reader',
            name='hall_id',
            field=models.ForeignKey(db_column='hall_id', on_delete=django.db.models.deletion.PROTECT, to='library_app.readinghall', verbose_name='Зал'),
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('book_author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_order', models.IntegerField(default=1, verbose_name='Порядок автора')),
                ('author_id', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='library_app.author')),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
            ],
            options={
                'db_table': 'BookAuthor',
                'ordering': ['author_order'],
                'unique_together': {('author_id', 'book_id')},
            },
        ),
    ]
