# Generated by Django 4.2.24 on 2025-09-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Toyota', 'Toyota'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Mercedes', 'Mercedes-Benz'), ('Volkswagen', 'Volkswagen'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia')], max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('state_number', models.CharField(max_length=20, unique=True, verbose_name='Государственный номер')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='Номер водительского удостоверения')),
                ('license_type', models.CharField(choices=[('A', 'Мотоциклы'), ('B', 'Легковые автомобили'), ('C', 'Грузовые автомобили'), ('D', 'Автобусы')], max_length=1, verbose_name='Тип категории')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverlicense', to='car_app.carowner', verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала владения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания владения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='car_app.car', verbose_name='Автомобиль')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='car_app.carowner', verbose_name='Владелец')),
            ],
        ),
    ]