# Generated by Django 5.2.8 on 2025-12-02 14:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название породы')),
                ('efficiency', models.PositiveIntegerField(verbose_name='Среднее количество яиц в месяц')),
                ('mean_weight', models.PositiveIntegerField(verbose_name='Средний вес (г)')),
            ],
            options={
                'verbose_name': 'Порода',
            },
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_number', models.PositiveIntegerField(verbose_name='Номер цеха')),
                ('row_number', models.PositiveIntegerField(verbose_name='Номер ряда')),
                ('in_row_number', models.PositiveIntegerField(verbose_name='Номер клетки в ряду')),
            ],
            options={
                'verbose_name': 'Клетка',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер диеты')),
                ('structure', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Диета',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО работника')),
                ('passport_series', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Серия паспорта должна содержать ровно 4 цифры', regex='^\\d{4}$')], verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Номер паспорта должен содержать ровно 6 цифр', regex='^\\d{6}$')], verbose_name='Номер паспорта')),
            ],
            options={
                'verbose_name': 'Работник',
            },
        ),
        migrations.CreateModel(
            name='BreedDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень')], max_length=6, verbose_name='Сезон')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_farm_app.breed', verbose_name='Порода')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_farm_app.diet', verbose_name='Диета')),
            ],
            options={
                'verbose_name': 'Диета породы',
                'unique_together': {('breed', 'diet', 'season')},
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='diets',
            field=models.ManyToManyField(related_name='breeds', through='poultry_farm_app.BreedDiet', to='poultry_farm_app.diet', verbose_name='Диеты по сезонам'),
        ),
        migrations.CreateModel(
            name='EmployeeCage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата, с которой сотрудник закреплён за клеткой')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата, с которой сотрудник откреплён от клетки')),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_farm_app.cage', verbose_name='Клетка')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_farm_app.employee', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Закрепление клетки за работником',
            },
        ),
        migrations.AddField(
            model_name='cage',
            name='employees',
            field=models.ManyToManyField(related_name='cages', through='poultry_farm_app.EmployeeCage', to='poultry_farm_app.employee', verbose_name='История обслуживания'),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('contract', models.CharField(max_length=30, unique=True, verbose_name='Номер договора найма')),
                ('salary_rub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата в рублях')),
                ('date_start', models.DateField(verbose_name='Дата вступления в должность')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('termination_reason', models.CharField(blank=True, choices=[('employee_initiative', 'Увольнение по инициативе сотрудника'), ('employer_initiative', 'Увольнение по инициативе работадателя'), ('mutual_agreement', 'Увольнение по соглашению сторон'), ('contract_expired', 'Истёк срок трудового договора'), ('uncontrollable_circumstances', 'Увольнение в связи с обстоятельствами, не зависящими от воли сторон')], max_length=30, null=True, verbose_name='Причина увольнения')),
                ('termination_order_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер приказа об увольнении')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='poultry_farm_app.employee', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Трудоустройство',
            },
        ),
        migrations.CreateModel(
            name='Hen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='Масса (г)')),
                ('birth_date', models.DateTimeField(verbose_name='Дата рождения')),
                ('death_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата смерти')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hens', to='poultry_farm_app.breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Курица',
            },
        ),
        migrations.CreateModel(
            name='HenCage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата заселения курицы в клетку')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата выселения курицы из клетки')),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_farm_app.cage', verbose_name='Клетка')),
                ('hen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry_farm_app.hen', verbose_name='Курица')),
            ],
            options={
                'verbose_name': 'Размещение курицы',
            },
        ),
        migrations.AddField(
            model_name='hen',
            name='cages',
            field=models.ManyToManyField(related_name='hens', through='poultry_farm_app.HenCage', to='poultry_farm_app.cage', verbose_name='История заселения'),
        ),
        migrations.AlterUniqueTogether(
            name='cage',
            unique_together={('workshop_number', 'row_number', 'in_row_number')},
        ),
        migrations.CreateModel(
            name='HenEggs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_eggs', models.PositiveIntegerField(verbose_name='Количество снесённых яиц')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_records', to='poultry_farm_app.hen', verbose_name='Курица')),
            ],
            options={
                'verbose_name': 'Яйценоскость',
                'unique_together': {('hen', 'date')},
            },
        ),
    ]
