# Generated by Django 6.0.2 on 2026-02-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Умение',
                'verbose_name_plural': 'Умения',
            },
        ),
        migrations.CreateModel(
            name='SkillOfWarrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Уровень освоения умения')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_of_warriors', to='warriors_app.skill', verbose_name='Умение')),
            ],
            options={
                'verbose_name': 'Умение воина',
                'verbose_name_plural': 'Умения воинов',
            },
        ),
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[('s', 'student'), ('d', 'developer'), ('t', 'teamlead')], max_length=1, verbose_name='Расса')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warriors', to='warriors_app.profession', verbose_name='Профессия')),
                ('skill', models.ManyToManyField(related_name='warrior_skills', through='warriors_app.SkillOfWarrior', to='warriors_app.skill', verbose_name='Умения')),
            ],
            options={
                'verbose_name': 'Воин',
                'verbose_name_plural': 'Воины',
            },
        ),
        migrations.AddField(
            model_name='skillofwarrior',
            name='warrior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='warriors_app.warrior', verbose_name='Воин'),
        ),
    ]
