# Generated by Django 6.0.1 on 2026-01-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10, verbose_name='Цена за сутки'),
            preserve_default=False,
        ),
    ]
