# Generated by Django 6.0.1 on 2026-01-26 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_remove_roomtype_price_per_night_roomtype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='max_guests',
            field=models.PositiveIntegerField(verbose_name='Вместимость (чел)'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за сутки'),
        ),
    ]
