# Generated by Django 4.2.25 on 2025-10-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirlineCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название компании"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.IntegerField(verbose_name="Номер рейса")),
                (
                    "departure_datetime",
                    models.DateTimeField(verbose_name="Дата и время вылета"),
                ),
                (
                    "arrival_datetime",
                    models.DateTimeField(verbose_name="Дата и время прилета"),
                ),
                (
                    "sold_tickets",
                    models.IntegerField(verbose_name="Количество проданных билетов"),
                ),
                (
                    "crew",
                    models.ManyToManyField(
                        to="main.crew", verbose_name="Экипаж, обслуживающий рейс"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance",
                    models.IntegerField(verbose_name="Расстояние до пункта назначения"),
                ),
                (
                    "departure_point",
                    models.CharField(max_length=255, verbose_name="Пункт вылета"),
                ),
                (
                    "destination_point",
                    models.CharField(max_length=255, verbose_name="Пункт назначения"),
                ),
                (
                    "landing_points",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Пункты посадки",
                    ),
                ),
                (
                    "transit_landings",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Транзитные посадки",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransitLanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "landing_point",
                    models.CharField(
                        max_length=255, verbose_name="Пункт транзитной посадки"
                    ),
                ),
                (
                    "landing_datetime",
                    models.DateTimeField(
                        verbose_name="Дата и время транзитной посадки"
                    ),
                ),
                (
                    "takeoff_datetime",
                    models.DateTimeField(
                        verbose_name="Дата и время вылета (после транзитной посадки)"
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.flight",
                        verbose_name="Рейс",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Номер самолета"),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Тип самолета")),
                ("seats_capacity", models.IntegerField(verbose_name="Число мест")),
                ("flight_speed", models.IntegerField(verbose_name="Скорость полета")),
                (
                    "in_repair",
                    models.BooleanField(default=False, verbose_name="В ремонте"),
                ),
                (
                    "airline_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.airlinecompany",
                        verbose_name="Компания-авиаперевозчик",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flight",
            name="plane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.plane",
                verbose_name="Самолет, обслуживающий рейс",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="main.route",
                verbose_name="Маршрут",
            ),
        ),
        migrations.CreateModel(
            name="CrewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                ("age", models.IntegerField(verbose_name="Возраст")),
                (
                    "education",
                    models.CharField(max_length=255, verbose_name="Образование"),
                ),
                ("work_experience", models.IntegerField(verbose_name="Стаж работы")),
                (
                    "passport_info",
                    models.CharField(max_length=255, verbose_name="Паспортные данные"),
                ),
                (
                    "flight_authorization",
                    models.BooleanField(default=False, verbose_name="Допуск к рейсу"),
                ),
                (
                    "position",
                    models.CharField(
                        max_length=50,
                        verbose_name="Должность (командир, второй пилот, штурман, стюардесса/стюард)",
                    ),
                ),
                (
                    "company",
                    models.ManyToManyField(
                        to="main.airlinecompany",
                        verbose_name="Компания, в которой работает",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crew",
            name="members",
            field=models.ManyToManyField(
                to="main.crewmember", verbose_name="Члены экипажа"
            ),
        ),
    ]
