# Generated by Django 4.2.25 on 2025-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_crewmember_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="arrival_point",
            field=models.CharField(
                default="Аляска", max_length=255, verbose_name="Пункт прилета"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="departure_point",
            field=models.CharField(
                default="Аляска", max_length=255, verbose_name="Пункт вылета"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="is_transit",
            field=models.BooleanField(default=False, verbose_name="Транзитный рейс"),
        ),
        migrations.DeleteModel(
            name="TransitLanding",
        ),
    ]
