# Generated by Django 4.2.25 on 2025-12-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_flight_arrival_point_flight_departure_point_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crewmember",
            name="company",
        ),
        migrations.AddField(
            model_name="crewmember",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crew_members",
                to="main.airlinecompany",
                verbose_name="Компания, в которой работает",
            ),
            preserve_default=False,
        ),
    ]
