# Generated by Django 4.2.25 on 2025-12-17 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_crewmember_company_crewmember_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewmember",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crew_members",
                to="main.airlinecompany",
                verbose_name="Компания, в которой работает",
            ),
        ),
    ]
