# Generated by Django 4.2.25 on 2025-12-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_crewmember_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flights",
                to="main.route",
                verbose_name="Маршрут",
            ),
        ),
    ]
