# Generated by Django 4.2.25 on 2025-12-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_flight_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="plane",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.plane",
                verbose_name="Самолет, обслуживающий рейс",
            ),
        ),
    ]
