# Generated by Django 4.2.25 on 2025-12-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_flight_plane"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plane",
            name="airline_company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.airlinecompany",
                verbose_name="Компания-авиаперевозчик",
            ),
        ),
    ]
