# Generated by Django 5.0 on 2025-09-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reserved_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата бронирования"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False, verbose_name="Подтверждено администратором"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tour_date", models.DateField(verbose_name="Дата тура")),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(verbose_name="Оценка тура (1-10)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название тура"),
                ),
                (
                    "agency",
                    models.CharField(max_length=150, verbose_name="Турагенство"),
                ),
                ("description", models.TextField(verbose_name="Описание тура")),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                ("start_date", models.DateField(verbose_name="Дата начала тура")),
                ("end_date", models.DateField(verbose_name="Дата окончания тура")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость тура"
                    ),
                ),
            ],
        ),
    ]
