# Generated by Django 5.0 on 2025-09-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Ожидает подтверждения"),
                    ("approved", "Подтверждено"),
                    ("refused", "Отклонено"),
                ],
                default="waiting",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
