# Generated by Django 6.0.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lab3_app", "0002_alter_room_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="booked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Оформил",
            ),
        ),
    ]
