# Generated by Django 5.2.7 on 2025-10-17 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceregistration',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('comment_type', models.CharField(choices=[('cooperation', 'Вопрос о сотрудничестве'), ('races', 'Вопрос о гонках'), ('other', 'Иное')], max_length=30)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winners.commentator')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winners.race')),
            ],
        ),
    ]
