# Generated by Django 5.2.7 on 2025-10-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0002_raceregistration_is_confirmed_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='comment_time',
        ),
    ]
