# Generated by Django 5.2.7 on 2025-10-18 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0003_rename_comment_date_comment_comment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('heat_time', models.DateTimeField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='winners.race')),
            ],
        ),
        migrations.CreateModel(
            name='HeatResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='winners.heat')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winners.racer')),
            ],
            options={
                'ordering': ['heat', 'position'],
                'unique_together': {('heat', 'racer')},
            },
        ),
    ]
