# Generated by Django 4.2.25 on 2025-11-10 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='racing.profile'),
        ),
        migrations.AlterField(
            model_name='racesession',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
