# Generated by Django 5.2.7 on 2025-11-02 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('has_occurred', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('team_name', models.CharField(max_length=100)),
                ('car_description', models.TextField()),
                ('experience', models.IntegerField()),
                ('racer_class', models.CharField(max_length=100)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racers', to='main.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'race')},
            },
        ),
    ]
