# Generated by Django 3.2.25 on 2025-10-31 23:12

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='flight',
            name='direction',
            field=models.CharField(choices=[('ARR', 'Прибытие'), ('DEP', 'Вылет')], max_length=3, verbose_name='Направление'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_dt'], name='core_flight_departu_89d4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['direction'], name='core_flight_directi_ec74b5_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['number'], name='core_flight_number_066199_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['flight'], name='core_review_flight__2e7253_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='core_review_rating_41e437_idx'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('seats_total__gte', 0)), name='seats_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('seats_available__gte', 0)), name='seats_avail_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('seats_available__lte', django.db.models.expressions.F('seats_total'))), name='seats_avail_lte_total'),
        ),
    ]
