# Generated by Django 5.2.6 on 2025-11-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_depot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
