# Generated by Django 5.2.6 on 2025-11-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrior',
            name='skill',
            field=models.ManyToManyField(related_name='warrior_skills', through='warriors_app.SkillOfWarrior', to='warriors_app.skill', verbose_name='Умения'),
        ),
    ]
