# Generated by Django 5.2.6 on 2025-11-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(max_length=15, verbose_name="Гос номер"),
                ),
                ("car_brand", models.CharField(max_length=20, verbose_name="Марка")),
                ("car_model", models.CharField(max_length=20, verbose_name="Модель")),
                (
                    "car_colour",
                    models.CharField(max_length=30, null=True, verbose_name="Цвет"),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
            },
        ),
        migrations.CreateModel(
            name="CarOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=30, verbose_name="Фамилия")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Автовладелец",
            },
        ),
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver_license_number",
                    models.CharField(
                        max_length=10, verbose_name="Номер водительского удостоверения"
                    ),
                ),
                (
                    "driver_license_type",
                    models.CharField(
                        max_length=10, verbose_name="Тип водительского удостоверения"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Дата выдачи")),
                (
                    "id_car_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_owners.carowner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Водительское удостоверение",
            },
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата начала"),
                ),
                (
                    "end_date",
                    models.DateTimeField(null=True, verbose_name="Дата окончания"),
                ),
                (
                    "id_car",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_owners.car",
                        verbose_name="id автомобиля",
                    ),
                ),
                (
                    "id_car_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_owners.carowner",
                        verbose_name="id владельца",
                    ),
                ),
            ],
            options={
                "verbose_name": "Владение",
            },
        ),
    ]
