# Generated by Django 5.2.6 on 2025-11-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_owners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownership",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="start_date",
            field=models.DateTimeField(verbose_name="Дата начала"),
        ),
    ]
