# Generated by Django 5.2.6 on 2025-11-24 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_owners", "0002_alter_ownership_end_date_alter_ownership_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverlicense",
            name="id_car_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_owner",
                to="car_owners.carowner",
                verbose_name="Владелец автомобиля",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="id_car",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to="car_owners.car",
                verbose_name="id автомобиля",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="id_car_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownership",
                to="car_owners.carowner",
                verbose_name="id владельца",
            ),
        ),
    ]
