# Generated by Django 5.2.7 on 2025-10-15 11:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avtomobil',
            fields=[
                ('id_avtomobilya', models.AutoField(primary_key=True, serialize=False)),
                ('gos_nomer', models.CharField(max_length=15, verbose_name='Гос. номер')),
                ('marka', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('cvet', models.CharField(max_length=30, null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'db_table': 'avtomobil',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('data_rozhdeniya', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер паспорта')),
                ('home_address', models.TextField(blank=True, null=True, verbose_name='Домашний адрес')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Национальность')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь (Владелец)',
                'verbose_name_plural': 'Пользователи (Владельцы)',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vladenie',
            fields=[
                ('id_vladeltsa_avto', models.AutoField(primary_key=True, serialize=False)),
                ('data_nachala', models.DateTimeField(verbose_name='Дата начала владения')),
                ('data_okonchaniya', models.DateTimeField(null=True, verbose_name='Дата окончания владения')),
                ('id_avtomobilya', models.ForeignKey(db_column='id_avtomobilya', null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.avtomobil', verbose_name='Автомобиль')),
                ('id_vladelca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Владение',
                'verbose_name_plural': 'Владения',
                'db_table': 'vladenie',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avtomobili',
            field=models.ManyToManyField(related_name='vladelcy', through='project_first_app.Vladenie', to='project_first_app.avtomobil', verbose_name='Автомобили'),
        ),
        migrations.CreateModel(
            name='Voditelskoe_udostoverenie',
            fields=[
                ('id_udostovereniya', models.AutoField(primary_key=True, serialize=False)),
                ('nomer_udostovereniya', models.CharField(max_length=10, verbose_name='Номер удостоверения')),
                ('tip', models.CharField(max_length=10, verbose_name='Тип')),
                ('data_vydachi', models.DateTimeField(verbose_name='Дата выдачи')),
                ('id_vladelca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Водительское удостоверение',
                'verbose_name_plural': 'Водительские удостоверения',
                'db_table': 'voditelskoe_udostoverenie',
            },
        ),
    ]
