# Generated by Django 5.1.1 on 2025-10-20 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=64, unique=True, verbose_name='Номер паспорта')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=64, verbose_name='Отчество')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=64, verbose_name='Отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер комнаты')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('room_type', models.CharField(choices=[('single', 'Одноместный'), ('double', 'Двухместный'), ('triple', 'Трёхместный')], max_length=10, verbose_name='Тип номера')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена/сутки')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон в номере')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Пн'), (2, 'Вт'), (3, 'Ср'), (4, 'Чт'), (5, 'Пт'), (6, 'Сб'), (7, 'Вс')], verbose_name='День недели')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='hotel.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Расписание сотрудника',
                'verbose_name_plural': 'Расписания сотрудников',
                'ordering': ['employee_id', 'weekday', 'floor'],
                'unique_together': {('employee', 'weekday', 'floor')},
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заселения')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='Дата выезда')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='hotel.client', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='hotel.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Проживание',
                'verbose_name_plural': 'Проживания',
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['room', 'check_in', 'check_out'], name='hotel_stay_room_id_e08651_idx'), models.Index(fields=['client', 'check_in', 'check_out'], name='hotel_stay_client__f82d0d_idx')],
            },
        ),
    ]
