# Generated by Django 5.2.6 on 2025-11-24 14:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Тип автобуса',
                'verbose_name_plural': 'Типы автобусов',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер маршрута')),
                ('start_point', models.CharField(max_length=100, verbose_name='Начальный пункт')),
                ('end_point', models.CharField(max_length=100, verbose_name='Конечный пункт')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('interval', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал движения (мин)')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Протяженность (мин)')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True, verbose_name='Номер')),
                ('is_active', models.BooleanField(verbose_name='Действующий')),
                ('purchase_date', models.DateField(verbose_name='Дата приобретения')),
                ('bus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='bus_depot_app.bustype', verbose_name='Тип автобуса')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобусы',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('passport', models.CharField(max_length=10, unique=True, verbose_name='Серия и номер паспорта')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('driver_class', models.CharField(choices=[('1', 'Первый класс'), ('2', 'Второй класс'), ('3', 'Третий класс')], max_length=1, verbose_name='Класс водителя')),
                ('experience', models.PositiveIntegerField(verbose_name='Стаж (лет)')),
                ('salary', models.PositiveIntegerField(verbose_name='Оклад')),
                ('main_bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_drivers', to='bus_depot_app.bus', verbose_name='Основной автобус')),
                ('main_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_drivers', to='bus_depot_app.route', verbose_name='Основной маршрут')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата работы')),
                ('start_time', models.TimeField(verbose_name='Время начала смены')),
                ('end_time', models.TimeField(verbose_name='Время окончания смены')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bus_depot_app.bus', verbose_name='Автобус')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bus_depot_app.driver', verbose_name='Водитель')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bus_depot_app.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Назначение водителя',
                'verbose_name_plural': 'График работы водителей',
            },
        ),
        migrations.CreateModel(
            name='BusStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('active', 'На линии'), ('not_active', 'Не на линии'), ('broken', 'Неисправность'), ('no_driver', 'Отсутствие водителя')], max_length=20, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина отсутствия')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='bus_depot_app.bus', verbose_name='Автобус')),
            ],
            options={
                'verbose_name': 'Статус автобуса',
                'verbose_name_plural': 'Статусы автобусов',
                'unique_together': {('bus', 'date')},
            },
        ),
    ]
