# Generated by Django 6.0 on 2026-01-27 07:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название книги')),
                ('authors', models.CharField(max_length=500, verbose_name='Автор(ы)')),
                ('publisher', models.CharField(max_length=200, verbose_name='Издательство')),
                ('publication_year', models.PositiveIntegerField(verbose_name='Год издания')),
                ('section', models.CharField(max_length=200, verbose_name='Раздел')),
                ('code', models.CharField(max_length=100, verbose_name='Шифр книги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True, verbose_name='Номер читательского билета')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Номер паспорта')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('education', models.CharField(choices=[('primary', 'Начальное'), ('secondary', 'Среднее'), ('higher', 'Высшее'), ('degree', 'Ученая степень')], max_length=20, verbose_name='Образование')),
                ('has_degree', models.BooleanField(default=False, verbose_name='Наличие ученой степени')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата записи в библиотеку')),
                ('unregistration_date', models.DateField(blank=True, null=True, verbose_name='Дата выписки из библиотеки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
                'ordering': ['ticket_number'],
            },
        ),
        migrations.CreateModel(
            name='ReadingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер зала')),
                ('name', models.CharField(max_length=200, verbose_name='Название зала')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Читальный зал',
                'verbose_name_plural': 'Читальные залы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='BookAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(auto_now_add=True, verbose_name='Дата закрепления')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Возвращена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.book', verbose_name='Книга')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_assignments', to='app.reader', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Закрепление книги',
                'verbose_name_plural': 'Закрепления книг',
                'ordering': ['-assignment_date'],
            },
        ),
        migrations.AddField(
            model_name='reader',
            name='reading_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readers', to='app.readingroom', verbose_name='Читальный зал'),
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество экземпляров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='app.book', verbose_name='Книга')),
                ('reading_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_copies', to='app.readingroom', verbose_name='Читальный зал')),
            ],
            options={
                'verbose_name': 'Экземпляр книги в зале',
                'verbose_name_plural': 'Экземпляры книг в залах',
                'ordering': ['book', 'reading_room'],
                'unique_together': {('book', 'reading_room')},
            },
        ),
    ]
