# Generated by Django 5.2.8 on 2025-11-26 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('section', models.CharField(max_length=255)),
                ('cipher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('reader_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateField(auto_now_add=True)),
                ('last_reregistration_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingHall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('book_author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='library_app.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='library_app.book')),
            ],
            options={
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='library_app.BookAuthor', to='library_app.author'),
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('copy_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', 'В наличии'), ('on_loan', 'Выдана'), ('written_off', 'Списана')], default='available', max_length=20)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_written_off', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='library_app.book')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_copies', to='library_app.readinghall')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library_app.bookcopy')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library_app.reader')),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readers', to='library_app.readinghall'),
        ),
    ]
