# Generated by Django 5.2.8 on 2025-11-26 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_readinghall_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'verbose_name': 'Автор книги', 'verbose_name_plural': 'Авторы книги'},
        ),
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'verbose_name': 'Экземпляр книги', 'verbose_name_plural': 'Экземпляры книг'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Выдача', 'verbose_name_plural': 'Выдачи'},
        ),
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name': 'Читатель', 'verbose_name_plural': 'Читатели'},
        ),
        migrations.AlterModelOptions(
            name='readinghall',
            options={'verbose_name': 'Читальный зал', 'verbose_name_plural': 'Читальные залы'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна ли книга'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cipher',
            field=models.CharField(max_length=100, verbose_name='Шифр книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=255, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.CharField(max_length=255, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='date_received',
            field=models.DateField(default='2025-01-01', verbose_name='Дата поступления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='date_written_off',
            field=models.DateField(blank=True, null=True, verbose_name='Дата списания'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.readinghall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'В наличии'), ('on_loan', 'Выдана'), ('written_off', 'Списана')], default='available', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='assigned_at',
            field=models.DateTimeField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.bookcopy', verbose_name='Экземпляр книги'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.reader', verbose_name='Читатель'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='card_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер читательского билета'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='education_level',
            field=models.CharField(max_length=50, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readers', to='library_app.readinghall', verbose_name='Закреплён за залом'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='last_reregistration_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней перерегистрации'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='passport_number',
            field=models.CharField(max_length=50, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='registered_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='readinghall',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='readinghall',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер зала'),
        ),
    ]
