# Generated by Django 5.2.8 on 2025-11-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_bookcopy_options_alter_bookcopy_copy_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'verbose_name': 'Экземпляр книги', 'verbose_name_plural': 'Экземпляры книги'},
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('on_loan', 'На руках'), ('written_off', 'Списан')], default='available', max_length=20, verbose_name='Статус экземпляра'),
        ),
    ]
