# Generated by Django 5.2.8 on 2025-11-29 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_alter_bookcopy_status_alter_loan_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи'),
        ),
    ]
