# Generated by Django 4.2.25 on 2025-11-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("license_plate", models.CharField(max_length=15)),
                ("brand", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=20)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=30)),
                ("birth_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.car",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("license_number", models.CharField(max_length=10)),
                ("license_type", models.CharField(max_length=10)),
                ("issue_date", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.owner",
                    ),
                ),
            ],
        ),
    ]
