# Generated by Django 4.2.25 on 2025-12-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverlicense",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="project_first_app.owner",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to="project_first_app.car",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to="project_first_app.owner",
            ),
        ),
    ]
