# Generated by Django 3.2.25 on 2025-11-03 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('due_date', models.DateField(verbose_name='Срок выполнения')),
                ('penalty_info', models.TextField(blank=True, verbose_name='Информация о штрафах')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(verbose_name='Текст решения')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('grade', models.IntegerField(choices=[(5, '5 - Отлично'), (4, '4 - Хорошо'), (3, '3 - Удовлетворительно'), (2, '2 - Неудовлетворительно'), (0, 'Не оценено')], default=0, verbose_name='Оценка')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Сдача задания',
                'verbose_name_plural': 'Сдачи заданий',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
