# Generated by Django 6.0.3 on 2026-03-05 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('grade', models.PositiveSmallIntegerField(default=1)),
                ('last_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('rank', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='exchange.applicant')),
            ],
            options={
                'ordering': ['-date_start'],
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='exchange.educationlevel'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='exchange.profession'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_experience_years', models.PositiveSmallIntegerField(default=0)),
                ('required_grade', models.PositiveSmallIntegerField(default=1)),
                ('salary_from', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salary_to', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_posted', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('additional_info', models.TextField(blank=True)),
                ('education_required', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies_required', to='exchange.educationlevel')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='exchange.employer')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='exchange.profession')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
