# Generated by Django 6.0 on 2025-12-08 02:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=50, unique=True, verbose_name='VIN')),
                ('make', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('leased', 'В аренде'), ('maintenance', 'На обслуживании'), ('sold', 'Продан')], default='available', max_length=20, verbose_name='Статус')),
                ('current_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Текущий пробег (км)')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, max_length=50, verbose_name='ИНН')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название автопарка')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес автопарка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Автопарк',
                'verbose_name_plural': 'Автопарки',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Компания сервиса',
                'verbose_name_plural': 'Компании сервиса',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид'), ('other', 'Другое')], default='petrol', max_length=20, verbose_name='Тип двигателя')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Объём двигателя (л)')),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)')),
                ('transmission', models.CharField(blank=True, choices=[('auto', 'Автомат'), ('manual', 'Механика'), ('cvt', 'Вариатор'), ('robot', 'Робот')], max_length=20, verbose_name='Коробка передач')),
                ('drivetrain', models.CharField(blank=True, choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный')], max_length=10, verbose_name='Привод')),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('suv', 'SUV'), ('wagon', 'Универсал'), ('van', 'Фургон'), ('coupe', 'Купе'), ('other', 'Другое')], max_length=20, verbose_name='Тип кузова')),
                ('fuel_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Расход топлива (л/100км)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('additional_options', models.TextField(blank=True, verbose_name='Дополнительные опции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='leasing_app.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Характеристики автомобиля',
                'verbose_name_plural': 'Характеристики автомобилей',
            },
        ),
        migrations.CreateModel(
            name='CarFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateField(blank=True, null=True, verbose_name='Дата прикрепления')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_fleet', to='leasing_app.car', verbose_name='Автомобиль')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='leasing_app.fleet', verbose_name='Автопарк')),
            ],
            options={
                'verbose_name': 'Принадлежность к автопарку',
                'verbose_name_plural': 'Принадлежность к автопаркам',
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ежемесячная оплата')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='leasing_app.car', verbose_name='Автомобиль')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='leasing_app.client', verbose_name='Клиент')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leases', to=settings.AUTH_USER_MODEL, verbose_name='Создал сотрудник')),
            ],
            options={
                'verbose_name': 'Договор аренды',
                'verbose_name_plural': 'Договоры аренды',
            },
        ),
        migrations.CreateModel(
            name='LeaseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_applications', to='leasing_app.car', verbose_name='Автомобиль')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_applications', to='leasing_app.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата обслуживания')),
                ('service', models.CharField(max_length=255, verbose_name='Вид обслуживания')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='leasing_app.car', verbose_name='Автомобиль')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Записал сотрудник')),
                ('maintenance_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='leasing_app.maintenancecompany', verbose_name='Сервис')),
            ],
            options={
                'verbose_name': 'Обслуживание',
                'verbose_name_plural': 'Обслуживания',
            },
        ),
    ]
