# Generated by Django 5.2.8 on 2025-11-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_book_publication_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={},
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='copy_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID экземпляра'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.readinghall', verbose_name='Читальный зал'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('on_loan', 'Выдан'), ('written_off', 'Списан')], default='available', max_length=20, verbose_name='Статус экземпляра'),
        ),
    ]
