# Generated by Django 5.2.8 on 2025-11-26 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_bookcopy_options_alter_bookcopy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('on_loan', 'На руках'), ('written_off', 'Списан')], default='available', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library_app.bookcopy', verbose_name='Экземпляр книги'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID выдачи'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library_app.reader', verbose_name='Читатель'),
        ),
    ]
