# Generated by Django 5.2.8 on 2025-11-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_alter_loan_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='has_academic_degree',
            field=models.BooleanField(default=False, verbose_name='Наличие учёной степени'),
        ),
    ]
