# Generated by Django 5.2.8 on 2025-12-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='cars',
            field=models.ManyToManyField(related_name='owners', through='project_first_app.Ownership', to='project_first_app.car'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания владения'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала владения'),
        ),
    ]
