# Generated by Django 4.2.27 on 2025-12-18 21:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество страниц')),
                ('has_illustrations', models.BooleanField(default=False, verbose_name='Наличие иллюстраций')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('cover_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на обложке')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Жанр')),
                ('language', models.CharField(default='RU', max_length=10, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-publication_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('company_name', models.CharField(blank=True, max_length=300, verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='Номер заказа')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает обработки'), ('PROCESSING', 'В обработке'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], default='PENDING', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Подытог')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='publishing.book', verbose_name='Книга')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='publishing.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
                'ordering': ['order', 'book'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(related_name='orders', through='publishing.OrderItem', to='publishing.book'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='publishing.customer', verbose_name='Заказчик'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('MANAGER', 'Менеджер'), ('EDITOR', 'Редактор'), ('OTHER', 'Другое')], default='OTHER', max_length=10, verbose_name='Роль')),
                ('position_title', models.CharField(max_length=200, verbose_name='Должность')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('user', models.OneToOneField(blank=True, help_text='Связь с учетной записью пользователя для аутентификации', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Номер контракта')),
                ('signed_date', models.DateField(verbose_name='Дата подписания')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активный'), ('COMPLETED', 'Завершен'), ('TERMINATED', 'Расторгнут')], default='DRAFT', max_length=15, verbose_name='Статус')),
                ('advance_payment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Аванс')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общий бюджет')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='publishing.book', verbose_name='Книга')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'MANAGER'}, on_delete=django.db.models.deletion.PROTECT, related_name='managed_contracts', to='publishing.employee', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ['-signed_date'],
            },
        ),
        migrations.CreateModel(
            name='BookEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chief_editor', models.BooleanField(default=False, verbose_name='Ответственный редактор')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_editors', to='publishing.book', verbose_name='Книга')),
                ('editor', models.ForeignKey(limit_choices_to={'role': 'EDITOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='edited_books', to='publishing.employee', verbose_name='Редактор')),
            ],
            options={
                'verbose_name': 'Редактор книги',
                'verbose_name_plural': 'Редакторы книг',
                'ordering': ['book', '-is_chief_editor', 'editor'],
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_order', models.IntegerField(help_text='Порядок автора на обложке книги (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок на обложке')),
                ('royalty_percentage', models.DecimalField(decimal_places=2, help_text='Процент от гонорара (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент гонорара')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='publishing.author', verbose_name='Автор')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='publishing.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Автор книги',
                'verbose_name_plural': 'Авторы книг',
                'ordering': ['book', 'author_order'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='publishing.BookAuthor', to='publishing.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='editors',
            field=models.ManyToManyField(related_name='edited_books_m2m', through='publishing.BookEditor', to='publishing.employee'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role'], name='publishing__role_b35dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['signed_date'], name='publishing__signed__9334dc_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='publishing__status_c5ea3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookeditor',
            unique_together={('book', 'editor')},
        ),
        migrations.AlterUniqueTogether(
            name='bookauthor',
            unique_together={('book', 'author'), ('book', 'author_order')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_date'], name='publishing__publica_741f09_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='publishing__isbn_6046ee_idx'),
        ),
    ]
