# Generated by Django 4.2.25 on 2025-12-29 06:12

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCards',
            fields=[
                ('id_card', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('balance', models.IntegerField()),
                ('discount_percent', models.IntegerField()),
                ('discount_rub', models.IntegerField()),
            ],
            options={
                'db_table': 'client_cards',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('type_company', models.IntegerField()),
                ('legal_address', models.CharField(max_length=100)),
                ('company_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='FuelPrices',
            fields=[
                ('id_fuel_price', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('per_liter', models.IntegerField()),
            ],
            options={
                'db_table': 'fuel_prices',
            },
        ),
        migrations.CreateModel(
            name='FuelReference',
            fields=[
                ('id_kind_fuel', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('burning_temp', models.IntegerField()),
                ('brand', models.CharField(max_length=40)),
                ('density', models.IntegerField()),
                ('season', models.IntegerField()),
                ('percent_sulfur', models.IntegerField()),
                ('min_usage_temp', models.IntegerField()),
            ],
            options={
                'db_table': 'fuel_reference',
            },
        ),
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id_station', models.AutoField(primary_key=True, serialize=False)),
                ('station_address', models.CharField(max_length=100)),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.companies')),
            ],
            options={
                'db_table': 'gas_station',
            },
        ),
        migrations.CreateModel(
            name='ProducedFuel',
            fields=[
                ('id_produced_fuel', models.AutoField(primary_key=True, serialize=False)),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.companies')),
                ('id_kind_fuel', models.ForeignKey(db_column='id_kind_fuel', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.fuelreference')),
            ],
            options={
                'db_table': 'produced_fuel',
            },
        ),
        migrations.CreateModel(
            name='SoldFuel',
            fields=[
                ('id_sold_fuel', models.AutoField(primary_key=True, serialize=False)),
                ('id_produced_fuel', models.ForeignKey(db_column='id_produced_fuel', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.producedfuel')),
                ('id_station', models.ForeignKey(db_column='id_station', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.gasstation')),
            ],
            options={
                'db_table': 'sold_fuel',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id_sales', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField()),
                ('sold_liters_volume', models.IntegerField()),
                ('id_card', models.ForeignKey(db_column='id_card', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.clientcards')),
                ('id_fuel_price', models.ForeignKey(db_column='id_fuel_price', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.fuelprices')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.AddField(
            model_name='fuelprices',
            name='id_sold_fuel',
            field=models.ForeignKey(db_column='id_sold_fuel', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.soldfuel'),
        ),
        migrations.AddField(
            model_name='clientcards',
            name='id_client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.clients'),
        ),
        migrations.AddField(
            model_name='clientcards',
            name='id_company',
            field=models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.companies'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='refueling_app.gasstation')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
