# Generated by Django 4.2.25 on 2025-12-26 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCards',
            fields=[
                ('id_card', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('balance', models.IntegerField()),
                ('discount_percent', models.IntegerField()),
                ('discount_rub', models.IntegerField()),
            ],
            options={
                'db_table': 'client_cards',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('type_company', models.IntegerField()),
                ('legal_address', models.CharField(max_length=100)),
                ('company_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='FuelPrices',
            fields=[
                ('id_fuel_price', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('per_liter', models.IntegerField()),
            ],
            options={
                'db_table': 'fuel_prices',
            },
        ),
        migrations.CreateModel(
            name='FuelReference',
            fields=[
                ('id_kind_fuel', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('burning_temp', models.IntegerField()),
                ('brand', models.CharField(max_length=40)),
                ('density', models.IntegerField()),
                ('season', models.IntegerField()),
                ('percent_sulfur', models.IntegerField()),
                ('min_usage_temp', models.IntegerField()),
            ],
            options={
                'db_table': 'fuel_reference',
            },
        ),
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id_station', models.AutoField(primary_key=True, serialize=False)),
                ('station_address', models.CharField(max_length=100)),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.companies')),
            ],
            options={
                'db_table': 'gas_station',
            },
        ),
        migrations.CreateModel(
            name='ProducedFuel',
            fields=[
                ('id_produced_fuel', models.AutoField(primary_key=True, serialize=False)),
                ('id_company', models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.companies')),
                ('id_kind_fuel', models.ForeignKey(db_column='id_kind_fuel', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.fuelreference')),
            ],
            options={
                'db_table': 'produced_fuel',
            },
        ),
        migrations.CreateModel(
            name='SoldFuel',
            fields=[
                ('id_sold_fuel', models.AutoField(primary_key=True, serialize=False)),
                ('id_produced_fuel', models.ForeignKey(db_column='id_produced_fuel', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.producedfuel')),
                ('id_station', models.ForeignKey(db_column='id_station', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.gasstation')),
            ],
            options={
                'db_table': 'sold_fuel',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id_sales', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField()),
                ('sold_liters_volume', models.IntegerField()),
                ('id_card', models.ForeignKey(db_column='id_card', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.clientcards')),
                ('id_fuel_price', models.ForeignKey(db_column='id_fuel_price', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.fuelprices')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.AddField(
            model_name='fuelprices',
            name='id_sold_fuel',
            field=models.ForeignKey(db_column='id_sold_fuel', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.soldfuel'),
        ),
        migrations.AddField(
            model_name='clientcards',
            name='id_client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.clients'),
        ),
        migrations.AddField(
            model_name='clientcards',
            name='id_company',
            field=models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, to='refueling_app.companies'),
        ),
    ]
