# Generated by Django 4.2.25 on 2025-12-29 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refueling_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gas_station',
        ),
        migrations.AddField(
            model_name='user',
            name='id_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='refueling_app.gasstation'),
            preserve_default=False,
        ),
    ]
