# Generated by Django 4.2.25 on 2026-01-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refueling_app', '0002_remove_user_gas_station_user_id_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcards',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientcards',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientcards',
            name='discount_rub',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelprices',
            name='per_liter',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelreference',
            name='burning_temp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelreference',
            name='density',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelreference',
            name='min_usage_temp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelreference',
            name='percent_sulfur',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sold_liters_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
