# Generated by Django 4.2.25 on 2026-01-08 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refueling_app', '0003_sales_amount_paid_alter_clientcards_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcards',
            name='id_client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='client_cards', to='refueling_app.clients'),
        ),
    ]
