# Generated by Django 4.2.25 on 2026-01-08 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refueling_app', '0004_alter_clientcards_id_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcards',
            name='id_company',
            field=models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='client_cards', to='refueling_app.companies'),
        ),
        migrations.AlterField(
            model_name='fuelprices',
            name='id_sold_fuel',
            field=models.ForeignKey(db_column='id_sold_fuel', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_prices', to='refueling_app.soldfuel'),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='id_company',
            field=models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='gas_station', to='refueling_app.companies'),
        ),
        migrations.AlterField(
            model_name='producedfuel',
            name='id_company',
            field=models.ForeignKey(db_column='id_company', on_delete=django.db.models.deletion.CASCADE, related_name='produced_fuel', to='refueling_app.companies'),
        ),
        migrations.AlterField(
            model_name='producedfuel',
            name='id_kind_fuel',
            field=models.ForeignKey(db_column='id_kind_fuel', on_delete=django.db.models.deletion.CASCADE, related_name='produced_fuel', to='refueling_app.fuelreference'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='id_card',
            field=models.ForeignKey(db_column='id_card', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='refueling_app.clientcards'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='id_fuel_price',
            field=models.ForeignKey(db_column='id_fuel_price', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='refueling_app.fuelprices'),
        ),
        migrations.AlterField(
            model_name='soldfuel',
            name='id_produced_fuel',
            field=models.ForeignKey(db_column='id_produced_fuel', on_delete=django.db.models.deletion.CASCADE, related_name='sold_fuel', to='refueling_app.producedfuel'),
        ),
        migrations.AlterField(
            model_name='soldfuel',
            name='id_station',
            field=models.ForeignKey(db_column='id_station', on_delete=django.db.models.deletion.CASCADE, related_name='sold_fuel', to='refueling_app.gasstation'),
        ),
    ]
