# Generated by Django 4.2.25 on 2026-01-09 04:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refueling_app', '0005_alter_clientcards_id_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcards',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientcards',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientcards',
            name='discount_rub',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientcards',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
