# Generated by Django 5.2.6 on 2025-10-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('participation_conditions', models.TextField(blank=True)),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_description', models.TextField(blank=True)),
                ('topics', models.ManyToManyField(blank=True, to='conferences.topic')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
