# Generated by Django 5.2.6 on 2025-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='topics',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='conference',
            name='topics',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
