# Generated by Django 5.2.6 on 2025-10-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_presentation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentation',
            old_name='topic',
            new_name='title',
        ),
    ]
