# Generated by Django 5.2.6 on 2025-10-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='recommendation',
            field=models.CharField(choices=[(None, 'Не оценено'), (True, 'Рекомендован'), (False, 'Не рекомендован')], default=None, max_length=10, null=True),
        ),
    ]
