# Generated by Django 5.2.6 on 2025-10-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_alter_presentation_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='recommendation',
            field=models.BooleanField(blank=True, choices=[(None, 'Не оценено'), (True, 'Рекомендован'), (False, 'Не рекомендован')], null=True),
        ),
    ]
