# Generated by Django 5.2.8 on 2025-11-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_drf_app', '0002_alter_ownership_id_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicense',
            name='id_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_license', to='simple_drf_app.carowner'),
        ),
    ]
