# Generated by Django 5.1.1 on 2025-12-21 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата зачисления'),
        ),
    ]
