# Generated by Django 5.1.1 on 2025-12-21 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='hired_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата приема'),
        ),
    ]
