# Generated by Django 4.2.7 on 2025-12-22 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('room_type', models.CharField(choices=[('single', 'Одноместный'), ('double', 'Двухместный'), ('triple', 'Трёхместный')], max_length=10, verbose_name='Тип номера')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за сутки')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('check_in_date', models.DateField(verbose_name='Дата заселения')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='Дата выселения')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='hotel.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('day_of_week', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День недели')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='hotel.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'График уборки',
                'verbose_name_plural': 'Графики уборки',
                'ordering': ['day_of_week', 'floor'],
                'unique_together': {('employee', 'floor', 'day_of_week')},
            },
        ),
    ]
