# Generated by Django 6.0.1 on 2026-01-26 17:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('dish_type', models.CharField(choices=[('appetizer', 'Закуска'), ('soup', 'Суп'), ('main', 'Основное блюдо'), ('dessert', 'Десерт'), ('drink', 'Напиток')], max_length=20, verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('stock_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе')),
                ('minimum_stock', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Необходимый запас')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу')),
                ('supplier', models.CharField(max_length=100, verbose_name='Поставщик')),
                ('ingredient_type', models.CharField(choices=[('meat', 'Мясо'), ('vegetable', 'Овощи'), ('dairy', 'Молочные продукты'), ('spice', 'Специи'), ('other', 'Другое')], max_length=20, verbose_name='Тип ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('received', 'Принят'), ('cooking', 'Готовится'), ('ready', 'Готов'), ('served', 'Выдан'), ('paid', 'Оплачен')], default='received', max_length=20, verbose_name='Статус')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Название должности')),
                ('minimum_wage', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная зарплата')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='restaurant_app.dish', verbose_name='Блюдо')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_dishes', to='restaurant_app.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент блюда',
                'verbose_name_plural': 'Ингредиенты блюд',
                'unique_together': {('dish', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', through='restaurant_app.DishIngredient', to='restaurant_app.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Особые пожелания')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_orders', to='restaurant_app.dish', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='restaurant_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Деталь заказа',
                'verbose_name_plural': 'Детали заказа',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('passport_data', models.CharField(max_length=20, verbose_name='Паспортные данные')),
                ('category', models.CharField(choices=[('chef', 'Шеф-повар'), ('cook', 'Повар'), ('waiter', 'Официант')], max_length=20, verbose_name='Категория')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оклад')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='restaurant_app.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер стола')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят')], default='free', max_length=20, verbose_name='Статус')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='restaurant_app.employee', verbose_name='Обслуживающий официант')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant_app.table', verbose_name='Стол'),
        ),
        migrations.CreateModel(
            name='ChefDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_chefs', to='restaurant_app.dish', verbose_name='Блюдо')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_dishes', to='restaurant_app.employee', verbose_name='Повар')),
            ],
            options={
                'verbose_name': 'Блюдо повара',
                'verbose_name_plural': 'Блюда поваров',
                'unique_together': {('employee', 'dish')},
            },
        ),
    ]
