# Generated by Django 5.2.8 on 2025-11-18 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название гонки')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата гонки')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место')),
                ('description', models.TextField(blank=True, verbose_name='Описание гонки')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('team_name', models.CharField(blank=True, max_length=200, verbose_name='Название команды')),
                ('description', models.TextField(blank=True, verbose_name='Описание участника')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('participant_class', models.CharField(choices=[('A', 'Класс A'), ('B', 'Класс B'), ('C', 'Класс C')], default='C', max_length=2, verbose_name='Класс участника')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название автомобиля')),
                ('description', models.TextField(blank=True, verbose_name='Описание автомобиля')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='racing.participantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('comment_type', models.CharField(choices=[('coop', 'Вопрос о сотрудничестве'), ('race', 'Вопрос о гонках'), ('other', 'Иное')], max_length=10, verbose_name='Тип комментария')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Рейтинг (1-10)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата комментария')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_comments', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='racing.race')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('finish_time_ms', models.BigIntegerField(blank=True, null=True, verbose_name='Время заезда (мс)')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция (место)')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='racing.car')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='racing.participantprofile')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='racing.race')),
            ],
            options={
                'unique_together': {('race', 'participant')},
            },
        ),
    ]
