# Generated by Django 3.2.25 on 2025-10-13 07:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название гонки')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Локация')),
                ('date', models.DateField(verbose_name='Дата гонки')),
            ],
            options={
                'verbose_name': 'Гонка',
                'verbose_name_plural': 'Гонки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('car_description', models.TextField(blank=True, verbose_name='Описание автомобиля')),
                ('description', models.TextField(blank=True, verbose_name='Описание участника')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('driver_class', models.CharField(choices=[('amateur', 'Любитель'), ('pro', 'Профессионал'), ('junior', 'Юниор'), ('senior', 'Сеньор')], default='amateur', max_length=20, verbose_name='Класс участника')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='races.team', verbose_name='Команда')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль участника',
                'verbose_name_plural': 'Профили участников',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_date', models.DateField(verbose_name='Дата заезда')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('comment_type', models.CharField(choices=[('cooperation', 'Вопрос о сотрудничестве'), ('race', 'Вопрос о гонках'), ('other', 'Иное')], default='other', max_length=20, verbose_name='Тип комментария')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_comments', to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='races.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='races.participantprofile', verbose_name='Участник')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='races.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Регистрация на гонку',
                'verbose_name_plural': 'Регистрации на гонку',
                'unique_together': {('participant', 'race')},
            },
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер заезда')),
                ('scheduled_at', models.DateTimeField(verbose_name='Время заезда')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция')),
                ('result_time', models.DurationField(blank=True, null=True, verbose_name='Результат (время)')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='races.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Заезд',
                'verbose_name_plural': 'Заезды',
                'ordering': ['number'],
                'unique_together': {('race', 'number')},
            },
        ),
    ]
